! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Main Program File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_Main.f90
! Time                 : Tue Sep 16 16:29:12 2014
! Working directory    : /home/charlesj/Desktop/CHECKOUT/kpp_boxmodel/extended_box_model_Exa2Green
! Equation file        : kpp.kpp
! Output root filename : kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! MAIN - Main program - driver routine
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PROGRAM kpp_Driver

  USE kpp_Model
  USE kpp_Initialize, ONLY: Initialize
  USE Wrap_NETCDF
  USE kpp_Parameters, ONLY: idim_spot, jdim_spot, kdim_spot, TAG
  USE omp_lib

  INCLUDE "mpif.h"

  REAL(kind=dp) :: T, DVAL(NSPEC)
  REAL(kind=dp) :: RSTATE(20)

  INTEGER :: i, nbit, act_hour

  REAL(kind=dp) :: starttime, endtime, meantime
  REAL(kind=dp) :: energy_ts_init, energy_ts_final
  REAL(kind=dp) :: device_energy_ts_init, device_energy_ts_final
  REAL(kind=dp) :: mean_device_energy_ts, mean_energy_ts
  REAL(kind=dp) :: energy_init, energy_final
  REAL(kind=dp) :: device_energy_init, device_energy_final

  !~~~> Initialization 

  ! get energy counter at startup
  call energy(energy_init)
  call device_energy(device_energy_init)

  STEPMIN = 0.0d0
  STEPMAX = 0.0d0

  mean_energy_ts = 0.0d0
  mean_device_energy_ts = 0.0d0
  meantime = 0.0d0
  nbit = 0

  DO i=1,NVAR
     RTOL(i) = 1.0d-2
     ATOL(i) = 1.0d-2
  END DO

  CALL Initialize()
  CALL InitSaveData()

  CALL OMP_SET_DYNAMIC(.FALSE.)

  DO act_hour=0,23

     TSTART = act_hour * 3600.0D0
     TEND = TSTART + 30*120.0D0

     ! Get all initial values on all of the idim*jdim*kdim boxes at time = act_hour
     CALL Get_Boxes(initial_conc_from_file, temperature_from_file, act_hour) 

     !~~~> Time loop
     T = TSTART
     kron: DO WHILE (T < TEND)

        ! get energy counter at startup
        call energy(energy_ts_init)
        call device_energy(device_energy_ts_init)

        starttime = MPI_WTIME()

        CHI = CHIBE( T/60.0d+00, 48.0d+00, 2.0d+00, TAG )

        TIME = T
        CALL GetMass( C, DVAL )

        !CALL Update_SUN() 

        CALL INTEGRATE( TIN = T, TOUT = T+DT, RSTATUS_U = RSTATE, &
             ICNTRL_U = (/ 0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /), NHOUR = act_hour )

        T = RSTATE(1)

        endtime = MPI_WTIME()
        meantime = meantime + endtime - starttime
        nbit = nbit + 1

        ! get energy counter at end
        call energy(energy_ts_final)
        call device_energy(device_energy_ts_final)

        mean_energy_ts = mean_energy_ts + energy_ts_final - energy_ts_init
        mean_device_energy_ts = mean_device_energy_ts + &
             device_energy_ts_final - device_energy_ts_init

     END DO kron
     !~~~> End Time loop

     WRITE(6,991) (T-TSTART)/(TEND-TSTART)*100, T,     &
          ( TRIM(SPC_NAMES(MONITOR(i))), VARTOT(MONITOR(i),idim_spot,jdim_spot,kdim_spot)/CFACTOR, i=1,NMONITOR )

     TIME = T
     CALL SaveData()

  END DO ! end act_hour loop

  CALL CloseSaveData()

  ! get energy counter at end
  call energy(energy_final)
  call device_energy(device_energy_final)

  WRITE(6,*) 'Total elapsed time (timestep) = ', meantime / nbit
  write(6,*) 'Energy (timestep) = ', mean_energy_ts / nbit, ' Joules'
  write(6,*) 'Device energy (timestep) = ', &
       mean_device_energy_ts / nbit, ' Joules'
  write(6,*) 'at rate: ', &
       (mean_energy_ts)/(meantime), ' Watts'
  write(6,*) 
  write(6,*) 'Nb iterations = ', nbit 
  write(6,*) 
  write(6,*) 'Energy = ', energy_final-energy_init, ' Joules'
  write(6,*) 'Device energy = ', device_energy_final - device_energy_init, ' Joules'

991 FORMAT(F6.1,'%. T=',E9.3,2X,200(A,'=',E11.4,'; '))

  !==============================================================================
contains
  !==============================================================================

  subroutine device_energy(e)
    implicit none
    real (kind=8), intent(out) :: e

    open(unit=50, file='/sys/cray/pm_counters/accel_energy' ,action='READ')
    read(50,*) e
    close(50)
  end subroutine device_energy

  subroutine energy(e)
    implicit none
    real (kind=8), intent(out) :: e

    open(unit=50, file='/sys/cray/pm_counters/energy' ,action='READ')
    read(50,*) e
    close(50)
  end subroutine energy

END PROGRAM kpp_Driver

! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


