!-------------------- BEGIN kppa_Serial_jacobian.f90 BEGIN -------------------
! @file kppa_Serial_jacobian.f90                                              
! @author charlesj                                                            
! @date 2015-02-10 15:56:47.457841                                            
! @brief The Jacobian of the chemical model                                   
!                                                                             
! The Jacobian of the chemical model                                          
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE kppa_Serial_jacobian

  USE kppa_Serial_parameters
  USE kppa_Serial_sparse

  IMPLICIT NONE





  CONTAINS

!------------------------------------ Jac ------------------------------------
! The Jacobian of variable species                                            
!                                                                             
! @param[in]     var  Variable species concentrations                         
! @param[in]     fix  Fixed species concentrations                            
! @param[in]     rct  Reaction rates                                          
! @param[out]    sjac The row-compressed sparse Jacobian                      
!-----------------------------------------------------------------------------
  SUBROUTINE Jac(var, fix, rct, sjac)
    IMPLICIT NONE

    REAL(8), INTENT(IN) :: var(NVAR)
    REAL(8), INTENT(IN) :: fix(NFIX)
    REAL(8), INTENT(IN) :: rct(NREACT)
    REAL(8), INTENT(OUT) :: sjac(JAC_LU_NZ)

    REAL(8) :: t0
    REAL(8) :: t1
    REAL(8) :: t2
    REAL(8) :: t3
    REAL(8) :: t4
    REAL(8) :: t5
    REAL(8) :: t6
    REAL(8) :: t7
    REAL(8) :: t8
    REAL(8) :: t9
    REAL(8) :: t10
    REAL(8) :: t11
    REAL(8) :: t12
    REAL(8) :: t13
    REAL(8) :: t14
    REAL(8) :: t15
    REAL(8) :: t16
    REAL(8) :: t17
    REAL(8) :: t18
    REAL(8) :: t19
    REAL(8) :: t20
    REAL(8) :: t21
    REAL(8) :: t22
    REAL(8) :: t23
    REAL(8) :: t24
    REAL(8) :: t25
    REAL(8) :: t26
    REAL(8) :: t27
    REAL(8) :: t28
    REAL(8) :: t29
    REAL(8) :: t30
    REAL(8) :: t31
    REAL(8) :: t32
    REAL(8) :: t33
    REAL(8) :: t34
    REAL(8) :: t35
    REAL(8) :: t36
    REAL(8) :: t37
    REAL(8) :: t38
    REAL(8) :: t39
    REAL(8) :: t40
    REAL(8) :: t41
    REAL(8) :: t42
    REAL(8) :: t43
    REAL(8) :: t44
    REAL(8) :: t45
    REAL(8) :: t46
    REAL(8) :: t47
    REAL(8) :: t48
    REAL(8) :: t49
    REAL(8) :: t50
    REAL(8) :: t51
    REAL(8) :: t52
    REAL(8) :: t53
    REAL(8) :: t54
    REAL(8) :: t55
    REAL(8) :: t56
    REAL(8) :: t57
    REAL(8) :: t58
    REAL(8) :: t59
    REAL(8) :: t60
    REAL(8) :: t61
    REAL(8) :: t62
    REAL(8) :: t63
    REAL(8) :: t64
    REAL(8) :: t65
    REAL(8) :: t66
    REAL(8) :: t67
    REAL(8) :: t68
    REAL(8) :: t69
    REAL(8) :: t70
    REAL(8) :: t71
    REAL(8) :: t72
    REAL(8) :: t73
    REAL(8) :: t74
    REAL(8) :: t75
    REAL(8) :: t76
    REAL(8) :: t77
    REAL(8) :: t78
    REAL(8) :: t79
    REAL(8) :: t80
    REAL(8) :: t81
    REAL(8) :: t82
    REAL(8) :: t83
    REAL(8) :: t84
    REAL(8) :: t85
    REAL(8) :: t86
    REAL(8) :: t87
    REAL(8) :: t88
    REAL(8) :: t89
    REAL(8) :: t90
    REAL(8) :: t91
    REAL(8) :: t92
    REAL(8) :: t93
    REAL(8) :: t94
    REAL(8) :: t95
    REAL(8) :: t96
    REAL(8) :: t97
    REAL(8) :: t98
    REAL(8) :: t99
    REAL(8) :: t100
    REAL(8) :: t101
    REAL(8) :: t102
    REAL(8) :: t103
    REAL(8) :: t104
    REAL(8) :: t105
    REAL(8) :: t106
    REAL(8) :: t107
    REAL(8) :: t108
    REAL(8) :: t109
    REAL(8) :: t110
    REAL(8) :: t111
    REAL(8) :: t112
    REAL(8) :: t113
    REAL(8) :: t114
    REAL(8) :: t115
    REAL(8) :: t116
    REAL(8) :: t117
    REAL(8) :: t118
    REAL(8) :: t119
    REAL(8) :: t120
    REAL(8) :: t121
    REAL(8) :: t122
    REAL(8) :: t123
    REAL(8) :: t124
    REAL(8) :: t125
    REAL(8) :: t126
    REAL(8) :: t127
    REAL(8) :: t128
    REAL(8) :: t129
    REAL(8) :: t130
    REAL(8) :: t131
    REAL(8) :: t132
    REAL(8) :: t133
    REAL(8) :: t134
    REAL(8) :: t135
    REAL(8) :: t136
    REAL(8) :: t137
    REAL(8) :: t138
    REAL(8) :: t139
    REAL(8) :: t140
    REAL(8) :: t141
    REAL(8) :: t142
    REAL(8) :: t143
    REAL(8) :: t144
    REAL(8) :: t145
    REAL(8) :: t146
    REAL(8) :: t147
    REAL(8) :: t148
    REAL(8) :: t149
    REAL(8) :: t150
    REAL(8) :: t151
    REAL(8) :: t152
    REAL(8) :: t153
    REAL(8) :: t154
    REAL(8) :: t155
    REAL(8) :: t156
    REAL(8) :: t157
    REAL(8) :: t158
    REAL(8) :: t159
    REAL(8) :: t160
    REAL(8) :: t161
    REAL(8) :: t162
    REAL(8) :: t163
    REAL(8) :: t164
    REAL(8) :: t165
    REAL(8) :: t166
    REAL(8) :: t167
    REAL(8) :: t168
    REAL(8) :: t169
    REAL(8) :: t170
    REAL(8) :: t171
    REAL(8) :: t172
    REAL(8) :: t173
    REAL(8) :: t174
    REAL(8) :: t175
    REAL(8) :: t176
    REAL(8) :: t177
    REAL(8) :: t178
    REAL(8) :: t179
    REAL(8) :: t180
    REAL(8) :: t181
    REAL(8) :: t182
    REAL(8) :: t183
    REAL(8) :: t184
    REAL(8) :: t185
    REAL(8) :: t186
    REAL(8) :: t187
    REAL(8) :: t188
    REAL(8) :: t189
    REAL(8) :: t190
    REAL(8) :: t191
    REAL(8) :: t192
    REAL(8) :: t193
    REAL(8) :: t194
    REAL(8) :: t195
    REAL(8) :: t196
    REAL(8) :: t197
    REAL(8) :: t198
    REAL(8) :: t199
    REAL(8) :: t200
    REAL(8) :: t201
    REAL(8) :: t202
    REAL(8) :: t203
    REAL(8) :: t204
    REAL(8) :: t205
    REAL(8) :: t206
    REAL(8) :: t207
    REAL(8) :: t208
    REAL(8) :: t209
    REAL(8) :: t210
    REAL(8) :: t211
    REAL(8) :: t212
    REAL(8) :: t213
    REAL(8) :: t214
    REAL(8) :: t215
    REAL(8) :: t216
    REAL(8) :: t217
    REAL(8) :: t218
    REAL(8) :: t219
    REAL(8) :: t220
    REAL(8) :: t221
    REAL(8) :: t222
    REAL(8) :: t223
    REAL(8) :: t224
    REAL(8) :: t225
    REAL(8) :: t226
    REAL(8) :: t227
    REAL(8) :: t228
    REAL(8) :: t229
    REAL(8) :: t230
    REAL(8) :: t231
    REAL(8) :: t232
    REAL(8) :: t233
    REAL(8) :: t234
    REAL(8) :: t235
    REAL(8) :: t236
    REAL(8) :: t237
    REAL(8) :: t238
    REAL(8) :: t239
    REAL(8) :: t240
    REAL(8) :: t241
    REAL(8) :: t242
    REAL(8) :: t243
    REAL(8) :: t244
    REAL(8) :: t245
    REAL(8) :: t246
    REAL(8) :: t247
    REAL(8) :: t248
    REAL(8) :: t249
    REAL(8) :: t250
    REAL(8) :: t251
    REAL(8) :: t252
    REAL(8) :: t253
    REAL(8) :: t254
    REAL(8) :: t255
    REAL(8) :: t256
    REAL(8) :: t257
    REAL(8) :: t258
    REAL(8) :: t259
    REAL(8) :: t260
    REAL(8) :: t261
    REAL(8) :: t262
    REAL(8) :: t263
    REAL(8) :: t264
    REAL(8) :: t265
    REAL(8) :: t266
    REAL(8) :: t267
    REAL(8) :: t268
    REAL(8) :: t269
    REAL(8) :: t270
    REAL(8) :: t271
    REAL(8) :: t272
    REAL(8) :: t273
    REAL(8) :: t274
    REAL(8) :: t275
    REAL(8) :: t276
    REAL(8) :: t277
    REAL(8) :: t278
    REAL(8) :: t279
    REAL(8) :: t280
    REAL(8) :: t281
    REAL(8) :: t282
    REAL(8) :: t283
    REAL(8) :: t284
    REAL(8) :: t285
    REAL(8) :: t286
    REAL(8) :: t287
    REAL(8) :: t288
    REAL(8) :: t289
    REAL(8) :: t290
    REAL(8) :: t291
    REAL(8) :: t292
    REAL(8) :: t293
    REAL(8) :: t294
    REAL(8) :: t295
    REAL(8) :: t296
    REAL(8) :: t297
    REAL(8) :: t298
    REAL(8) :: t299
    REAL(8) :: t300
    REAL(8) :: t301
    REAL(8) :: t302
    REAL(8) :: t303
    REAL(8) :: t304
    REAL(8) :: t305
    REAL(8) :: t306
    REAL(8) :: t307
    REAL(8) :: t308
    REAL(8) :: t309
    REAL(8) :: t310
    REAL(8) :: t311
    REAL(8) :: t312
    REAL(8) :: t313
    REAL(8) :: t314
    REAL(8) :: t315
    REAL(8) :: t316
    REAL(8) :: t317
    REAL(8) :: t318
    REAL(8) :: t319
    REAL(8) :: t320
    REAL(8) :: t321
    REAL(8) :: t322
    REAL(8) :: t323
    REAL(8) :: t324
    REAL(8) :: t325
    REAL(8) :: t326
    REAL(8) :: t327
    REAL(8) :: t328
    REAL(8) :: t329
    REAL(8) :: t330
    REAL(8) :: t331
    REAL(8) :: t332
    REAL(8) :: t333
    REAL(8) :: t334
    REAL(8) :: t335
    REAL(8) :: t336
    REAL(8) :: t337
    REAL(8) :: t338
    REAL(8) :: t339
    REAL(8) :: t340
    REAL(8) :: t341
    REAL(8) :: t342
    REAL(8) :: t343
    REAL(8) :: t344
    REAL(8) :: t345
    REAL(8) :: t346
    REAL(8) :: t347
    REAL(8) :: t348
    REAL(8) :: t349
    REAL(8) :: t350
    REAL(8) :: t351
    REAL(8) :: t352
    REAL(8) :: t353
    REAL(8) :: t354

    t0 = 0
    t1 = rct(24)*var(27)
    t2 = rct(51)*var(80)
    t3 = 1.0e-10*var(80)
    t4 = rct(53)*var(80)
    t5 = rct(76)
    t6 = rct(4)
    t7 = 5.8e-11*var(80)
    t8 = rct(54)*var(80)
    t9 = rct(48)*var(80)
    t10 = rct(42)
    t11 = rct(43)
    t12 = 3.0e-11*var(80)
    t13 = rct(187)*var(76)
    t14 = rct(188)*var(80)
    t15 = rct(189)*var(80)
    t16 = rct(58)*var(80)
    t17 = rct(59)*var(80)
    t18 = rct(52)*var(80)
    t19 = rct(186)*var(80)
    t20 = 2.5e-12*var(80)
    t21 = 2.5e-12*var(80)
    t22 = 2.5e-12*var(80)
    t23 = rct(24)*var(2)
    t24 = rct(25)*var(41)
    t25 = 2.14e-10*var(67)
    t26 = rct(15)
    t27 = 1.0e-11*var(80)
    t28 = rct(182)
    t29 = 3.6e-12*var(80)
    t30 = rct(13)
    t31 = 1.0e-11*var(80)
    t32 = rct(50)*var(80)
    t33 = 4.0e-11*var(80)
    t34 = 2.2e-11*var(76)
    t35 = 3.0e-12*var(80)
    t36 = rct(6)
    t37 = rct(46)*var(80)
    t38 = rct(70)*var(80)
    t39 = rct(74)
    t40 = rct(22)*var(41)
    t41 = rct(23)*var(75)
    t42 = rct(9)
    t43 = rct(34)*var(80)
    t44 = rct(55)*var(80)
    t45 = rct(97)*var(76)
    t46 = rct(101)*var(79)
    t47 = rct(171)*var(78)
    t48 = rct(172)*var(77)
    t49 = 4.0e-12*var(39)
    t50 = 1.3e-11*var(80)
    t51 = rct(22)*var(36)
    t52 = rct(25)*var(27)
    t53 = rct(36)*var(78)**2.0
    t54 = rct(5)
    t55 = rct(45)*var(80)
    t56 = rct(155)*var(80)
    t57 = rct(156)*var(76)
    t58 = rct(157)*var(79)
    t59 = rct(49)*var(80)
    t60 = 1.7e-10*var(80)
    t61 = 1.22e-11*var(76)
    t62 = 2.0e-16*var(79)
    t63 = rct(56)*var(80)
    t64 = rct(98)*var(76)
    t65 = rct(102)*var(79)
    t66 = rct(72)*var(80)
    t67 = 5.81e-13*var(76)
    t68 = rct(104)*var(79)
    t69 = rct(148)*var(75)
    t70 = rct(149)*var(77)
    t71 = rct(150)*var(74)
    t72 = rct(151)*var(82)
    t73 = rct(17)
    t74 = rct(18)
    t75 = 1.15e-11*var(80)
    t76 = rct(93)*var(76)
    t77 = rct(87)*var(78)
    t78 = rct(116)*var(77)
    t79 = rct(130)*var(74)
    t80 = rct(142)*var(82)
    t81 = rct(176)*var(80)
    t82 = rct(177)*var(79)
    t83 = rct(20)
    t84 = 2.8e-11*var(80)
    t85 = rct(95)*var(76)
    t86 = rct(79)*var(78)
    t87 = rct(108)*var(77)
    t88 = rct(122)*var(74)
    t89 = rct(134)*var(82)
    t90 = rct(80)*var(78)
    t91 = rct(109)*var(77)
    t92 = rct(123)*var(74)
    t93 = rct(135)*var(82)
    t94 = rct(83)*var(78)
    t95 = rct(112)*var(77)
    t96 = rct(126)*var(74)
    t97 = rct(138)*var(82)
    t98 = rct(16)
    t99 = rct(63)*var(80)
    t100 = rct(81)*var(78)
    t101 = rct(110)*var(77)
    t102 = rct(124)*var(74)
    t103 = rct(136)*var(82)
    t104 = rct(82)*var(78)
    t105 = rct(111)*var(77)
    t106 = rct(125)*var(74)
    t107 = rct(137)*var(82)
    t108 = rct(144)*var(77)
    t109 = rct(145)*var(74)
    t110 = rct(146)*var(82)
    t111 = rct(147)*var(78)
    t112 = rct(86)*var(78)
    t113 = rct(115)*var(77)
    t114 = rct(129)*var(74)
    t115 = rct(141)*var(82)
    t116 = rct(14)
    t117 = 1.0e-11*var(80)
    t118 = rct(178)*var(78)
    t119 = rct(179)*var(77)
    t120 = 4.0e-12*var(62)
    t121 = rct(181)*var(75)
    t122 = rct(90)*var(78)
    t123 = rct(118)*var(77)
    t124 = rct(152)*var(74)
    t125 = rct(153)*var(82)
    t126 = 2.0*rct(154)*var(63)
    t127 = rct(19)
    t128 = 1.7e-11*var(80)
    t129 = rct(94)*var(76)
    t130 = rct(10)
    t131 = rct(11)
    t132 = 9.0e-12*var(80)
    t133 = rct(91)*var(76)
    t134 = 4.7e-12*var(75)
    t135 = rct(85)*var(78)
    t136 = rct(117)*var(77)
    t137 = rct(131)*var(74)
    t138 = rct(143)*var(82)
    t139 = 2.14e-10*var(27)
    t140 = rct(33)*var(77)**2.0
    t141 = 4.0e-12*var(78)
    t142 = 1.5e-11*var(77)
    t143 = rct(168)*var(74)
    t144 = rct(169)*var(82)
    t145 = 1.2e-12*var(76)
    t146 = 4.0e-12*var(78)
    t147 = 1.5e-11*var(77)
    t148 = rct(160)*var(74)
    t149 = rct(161)*var(82)
    t150 = 1.2e-12*var(76)
    t151 = rct(57)*var(80)
    t152 = rct(99)*var(76)
    t153 = rct(103)*var(79)
    t154 = rct(89)*var(78)
    t155 = rct(113)*var(77)
    t156 = rct(127)*var(74)
    t157 = rct(139)*var(82)
    t158 = rct(12)
    t159 = rct(62)*var(80)
    t160 = rct(92)*var(76)
    t161 = rct(88)*var(78)
    t162 = rct(106)*var(77)
    t163 = rct(120)*var(74)
    t164 = rct(132)*var(82)
    t165 = rct(77)*var(78)
    t166 = rct(105)*var(77)
    t167 = 2.0*rct(119)*var(74)
    t168 = rct(120)*var(73)
    t169 = rct(121)*var(81)
    t170 = rct(122)*var(53)
    t171 = rct(123)*var(54)
    t172 = rct(124)*var(57)
    t173 = rct(125)*var(58)
    t174 = rct(126)*var(55)
    t175 = rct(127)*var(71)
    t176 = rct(128)*var(82)
    t177 = rct(129)*var(60)
    t178 = rct(130)*var(50)
    t179 = rct(131)*var(66)
    t180 = rct(145)*var(59)
    t181 = rct(150)*var(48)
    t182 = rct(152)*var(63)
    t183 = rct(160)*var(69)
    t184 = rct(168)*var(68)
    t185 = rct(1)
    t186 = rct(23)*var(36)
    t187 = rct(31)*var(77)
    t188 = rct(37)*var(79)
    t189 = rct(39)*var(76)
    t190 = rct(41)*var(76)
    t191 = rct(44)*var(80)
    t192 = rct(73)*var(82)
    t193 = 4.7e-12*var(66)
    t194 = rct(148)*var(48)
    t195 = rct(181)*var(62)
    t196 = rct(7)
    t197 = rct(8)
    t198 = rct(38)*var(78)
    t199 = rct(39)*var(75)
    t200 = 2.5e-12*var(77)
    t201 = rct(41)*var(75)
    t202 = rct(91)*var(65)
    t203 = rct(92)*var(72)
    t204 = rct(93)*var(49)
    t205 = rct(94)*var(64)
    t206 = rct(95)*var(52)
    t207 = 2.2e-11*var(32)
    t208 = rct(97)*var(38)
    t209 = rct(98)*var(46)
    t210 = rct(99)*var(70)
    t211 = 5.81e-13*var(47)
    t212 = rct(156)*var(43)
    t213 = 1.2e-12*var(69)
    t214 = 1.22e-11*var(45)
    t215 = 1.2e-12*var(68)
    t216 = rct(187)*var(19)
    t217 = rct(29)*var(79)
    t218 = rct(30)*var(78)
    t219 = rct(31)*var(75)
    t220 = 2.0*rct(32)*var(77)
    t221 = 2.0*rct(33)*var(67)*var(77)
    t222 = 2.5e-12*var(76)
    t223 = rct(47)*var(80)
    t224 = rct(105)*var(74)
    t225 = rct(106)*var(73)
    t226 = rct(107)*var(81)
    t227 = rct(108)*var(53)
    t228 = rct(109)*var(54)
    t229 = rct(110)*var(57)
    t230 = rct(111)*var(58)
    t231 = rct(112)*var(55)
    t232 = rct(113)*var(71)
    t233 = rct(114)*var(82)
    t234 = rct(115)*var(60)
    t235 = rct(116)*var(50)
    t236 = rct(117)*var(66)
    t237 = rct(118)*var(63)
    t238 = rct(144)*var(59)
    t239 = rct(149)*var(48)
    t240 = 1.5e-11*var(69)
    t241 = 1.5e-11*var(68)
    t242 = rct(172)*var(39)
    t243 = rct(179)*var(62)
    t244 = rct(27)*var(79)
    t245 = rct(30)*var(77)
    t246 = rct(35)*var(80)
    t247 = 2.0*rct(36)*var(41)*var(78)
    t248 = rct(38)*var(76)
    t249 = rct(77)*var(74)
    t250 = rct(78)*var(81)
    t251 = rct(79)*var(53)
    t252 = rct(80)*var(54)
    t253 = rct(81)*var(57)
    t254 = rct(82)*var(58)
    t255 = rct(83)*var(55)
    t256 = rct(84)*var(82)
    t257 = rct(85)*var(66)
    t258 = rct(86)*var(60)
    t259 = rct(87)*var(50)
    t260 = rct(88)*var(73)
    t261 = rct(89)*var(71)
    t262 = rct(90)*var(63)
    t263 = rct(147)*var(59)
    t264 = 4.0e-12*var(69)
    t265 = 4.0e-12*var(68)
    t266 = rct(171)*var(39)
    t267 = rct(178)*var(62)
    t268 = rct(2)
    t269 = rct(3)
    t270 = rct(27)*var(78)
    t271 = rct(28)*var(80)
    t272 = rct(29)*var(77)
    t273 = rct(37)*var(75)
    t274 = rct(101)*var(38)
    t275 = rct(102)*var(46)
    t276 = rct(103)*var(70)
    t277 = rct(104)*var(47)
    t278 = rct(157)*var(43)
    t279 = 2.0e-16*var(45)
    t280 = rct(177)*var(51)
    t281 = rct(28)*var(79)
    t282 = rct(34)*var(37)
    t283 = rct(35)*var(78)
    t284 = rct(44)*var(75)
    t285 = rct(45)*var(42)
    t286 = rct(46)*var(34)
    t287 = rct(47)*var(77)
    t288 = rct(48)*var(16)
    t289 = rct(49)*var(44)
    t290 = rct(50)*var(31)
    t291 = rct(51)*var(9)
    t292 = rct(52)*var(22)
    t293 = rct(53)*var(11)
    t294 = rct(54)*var(15)
    t295 = rct(55)*var(38)
    t296 = rct(56)*var(46)
    t297 = rct(57)*var(70)
    t298 = rct(58)*var(20)
    t299 = rct(59)*var(21)
    t300 = 4.0e-11*var(32)
    t301 = 9.0e-12*var(65)
    t302 = rct(62)*var(72)
    t303 = rct(63)*var(56)
    t304 = 1.15e-11*var(49)
    t305 = 1.7e-11*var(64)
    t306 = 2.8e-11*var(52)
    t307 = 1.0e-11*var(30)
    t308 = 1.0e-11*var(61)
    t309 = 1.0e-11*var(28)
    t310 = rct(70)*var(35)
    t311 = rct(71)*var(83)
    t312 = rct(72)*var(47)
    t313 = rct(155)*var(43)
    t314 = 1.7e-10*var(45)
    t315 = 1.0e-10*var(10)
    t316 = 1.3e-11*var(40)
    t317 = rct(176)*var(51)
    t318 = 3.6e-12*var(29)
    t319 = 3.0e-11*var(18)
    t320 = 3.0e-12*var(33)
    t321 = rct(186)*var(23)
    t322 = rct(188)*var(19)
    t323 = rct(189)*var(19)
    t324 = 5.8e-11*var(14)
    t325 = 2.5e-12*var(24)
    t326 = 2.5e-12*var(25)
    t327 = 2.5e-12*var(26)
    t328 = rct(78)*var(78)
    t329 = rct(107)*var(77)
    t330 = rct(121)*var(74)
    t331 = rct(133)*var(82)
    t332 = rct(73)*var(75)
    t333 = rct(84)*var(78)
    t334 = rct(114)*var(77)
    t335 = rct(128)*var(74)
    t336 = rct(132)*var(73)
    t337 = rct(133)*var(81)
    t338 = rct(134)*var(53)
    t339 = rct(135)*var(54)
    t340 = rct(136)*var(57)
    t341 = rct(137)*var(58)
    t342 = rct(138)*var(55)
    t343 = rct(139)*var(71)
    t344 = 2.0*rct(140)*var(82)
    t345 = rct(141)*var(60)
    t346 = rct(142)*var(50)
    t347 = rct(143)*var(66)
    t348 = rct(146)*var(59)
    t349 = rct(151)*var(48)
    t350 = rct(153)*var(63)
    t351 = rct(161)*var(69)
    t352 = rct(169)*var(68)
    t353 = rct(21)
    t354 = rct(71)*var(80)

    sjac(1) = 0
    sjac(2) = 0
    sjac(3) = 0
    sjac(4) = t9
    sjac(5) = t288
    sjac(6) = 0
    sjac(7) = 0.4*t46
    sjac(8) = 0.01*t62
    sjac(9) = 0.2*t65
    sjac(10) = 0.28*t68
    sjac(11) = 0.45*t82
    sjac(12) = 0.06*t153
    sjac(13) = 0.4*t274 + 0.2*t275 + 0.06*t276 + 0.28*t277 + 0.01*t279 + &
        0.45*t280
    sjac(14) = 0
    sjac(15) = 0.07*t62
    sjac(16) = 0.2*t65
    sjac(17) = 0.5*t89
    sjac(18) = 0.5*t93
    sjac(19) = 0.5*t97
    sjac(20) = 0.5*t103
    sjac(21) = 0.5*t107
    sjac(22) = 0.5*t125
    sjac(23) = 0.5*t137
    sjac(24) = 0.29*t153
    sjac(25) = 0.5*t157
    sjac(26) = 0.5*t164
    sjac(27) = 0.5*t176 + 0.5*t179
    sjac(28) = 0.2*t275 + 0.29*t276 + 0.07*t279
    sjac(29) = 0.5*t331
    sjac(30) = 0.5*t335 + 0.5*t336 + 0.5*t337 + 0.5*t338 + 0.5*t339 + &
        0.5*t340 + 0.5*t341 + 0.5*t342 + 0.5*t343 + 0.5*t350
    sjac(31) = 0
    sjac(32) = 0.0054433*t16
    sjac(33) = 0.04417*t17
    sjac(34) = 1.075*t20
    sjac(35) = 0.08103*t56 + 0.08103*t57 + 0.83663*t58
    sjac(36) = 0.08103*t60 + 0.08103*t61 + 0.08103*t62
    sjac(37) = 0.00105*t63 + 0.00105*t64 + 0.00105*t65
    sjac(38) = 0.0034*t66 + 0.0034*t68
    sjac(39) = 0.007*t151 + 0.007*t152 + 0.007*t153
    sjac(40) = 0.00105*t209 + 0.007*t210 + 0.08103*t212 + 0.08103*t214
    sjac(41) = 0.00105*t275 + 0.007*t276 + 0.0034*t277 + 0.83663*t278 + &
        0.08103*t279
    sjac(42) = 0.00105*t296 + 0.007*t297 + 0.0054433*t298 + 0.04417*t299 + &
        0.0034*t312 + 0.08103*t313 + 0.08103*t314 + 1.075*t325
    sjac(43) = 0
    sjac(44) = t26
    sjac(45) = 0
    sjac(46) = t130
    sjac(47) = -t2
    sjac(48) = -t291
    sjac(49) = -t3
    sjac(50) = t48
    sjac(51) = t242
    sjac(52) = -t315
    sjac(53) = -t4
    sjac(54) = -t293
    sjac(55) = -t5
    sjac(56) = t134
    sjac(57) = t193
    sjac(58) = -t6
    sjac(59) = t246
    sjac(60) = t283
    sjac(61) = -t7
    sjac(62) = 0.4*t15
    sjac(63) = 0.4*t323 - t324
    sjac(64) = -t8
    sjac(65) = -t294
    sjac(66) = 0.6*t7
    sjac(67) = -t9
    sjac(68) = t13 + t14 + 0.6*t15
    sjac(69) = t216
    sjac(70) = -t288 + t322 + 0.6*t323 + 0.6*t324
    sjac(71) = -t10 - t11
    sjac(72) = t190
    sjac(73) = t201
    sjac(74) = -t12
    sjac(75) = t119
    sjac(76) = t243
    sjac(77) = -t319
    sjac(78) = -t13 - t14 - t15
    sjac(79) = -t216
    sjac(80) = -t322 - t323
    sjac(81) = -t16
    sjac(82) = -t298
    sjac(83) = -t17
    sjac(84) = -t299
    sjac(85) = -t18
    sjac(86) = -t292
    sjac(87) = -t19
    sjac(88) = t50
    sjac(89) = t316 - t321
    sjac(90) = 0.2033*t8
    sjac(91) = 0.1314*t16
    sjac(92) = 0.17667*t17
    sjac(93) = -t20
    sjac(94) = 1.075*t21
    sjac(95) = 0.06936*t56 + 0.06936*t57 + 0.06936*t58
    sjac(96) = 0.06936*t60 + 0.06936*t61 + 0.06936*t62
    sjac(97) = 0.0021*t63 + 0.0021*t64 + 0.0021*t65
    sjac(98) = 0.01133*t66 + 0.01133*t68
    sjac(99) = 0.01353*t151 + 0.01353*t152 + 0.01353*t153
    sjac(100) = 0.0021*t209 + 0.01353*t210 + 0.06936*t212 + 0.06936*t214
    sjac(101) = 0.0021*t275 + 0.01353*t276 + 0.01133*t277 + 0.06936*t278 + &
        0.06936*t279
    sjac(102) = 0.2033*t294 + 0.0021*t296 + 0.01353*t297 + 0.1314*t298 + &
        0.17667*t299 + 0.01133*t312 + 0.06936*t313 + 0.06936*t314 - t325 + &
        1.075*t326
    sjac(103) = 0.3833*t16
    sjac(104) = 0.22083*t17
    sjac(105) = -t21
    sjac(106) = 1.075*t22
    sjac(107) = 0.27087*t56 + 0.27087*t57 + 0.27087*t58
    sjac(108) = 0.27087*t60 + 0.27087*t61 + 0.27087*t62
    sjac(109) = 0.014*t63 + 0.014*t64 + 0.014*t65
    sjac(110) = 0.0056667*t66 + 0.0056667*t68
    sjac(111) = 0.04013*t151 + 0.04013*t152 + 0.04013*t153
    sjac(112) = 0.014*t209 + 0.04013*t210 + 0.27087*t212 + 0.27087*t214
    sjac(113) = 0.014*t275 + 0.04013*t276 + 0.0056667*t277 + 0.27087*t278 + &
        0.27087*t279
    sjac(114) = 0.014*t296 + 0.04013*t297 + 0.3833*t298 + 0.22083*t299 + &
        0.0056667*t312 + 0.27087*t313 + 0.27087*t314 - t326 + 1.075*t327
    sjac(115) = 0.49289*t16
    sjac(116) = 0.30917*t17
    sjac(117) = -t22
    sjac(118) = 0.459*t56 + 0.459*t57 + 0.459*t58
    sjac(119) = 0.459*t60 + 0.459*t61 + 0.459*t62
    sjac(120) = 0.0525*t63 + 0.0525*t64 + 0.0525*t65
    sjac(121) = 0.11667*t151 + 0.11667*t152 + 0.11667*t153
    sjac(122) = 0.0525*t209 + 0.11667*t210 + 0.459*t212 + 0.459*t214
    sjac(123) = 0.0525*t275 + 0.11667*t276 + 0.459*t278 + 0.459*t279
    sjac(124) = 0.0525*t296 + 0.11667*t297 + 0.49289*t298 + 0.30917*t299 + &
        0.459*t313 + 0.459*t314 - t327
    sjac(125) = -t1
    sjac(126) = -t23 - t24 - t25
    sjac(127) = -t52
    sjac(128) = -t139
    sjac(129) = t268
    sjac(130) = -t26 - t27
    sjac(131) = t233
    sjac(132) = -t309
    sjac(133) = t334
    sjac(134) = -t28 - t29
    sjac(135) = t121
    sjac(136) = t195
    sjac(137) = -t318
    sjac(138) = -t30 - t31
    sjac(139) = t166
    sjac(140) = t224
    sjac(141) = -t307
    sjac(142) = -t32
    sjac(143) = 0.06*t65
    sjac(144) = 0.09*t153
    sjac(145) = 0.06*t275 + 0.09*t276
    sjac(146) = -t290
    sjac(147) = 0.25*t16
    sjac(148) = 0.17*t17
    sjac(149) = -t33 - 0.5*t34
    sjac(150) = -0.5*t207
    sjac(151) = 0.25*t298 + 0.17*t299 - t300
    sjac(152) = t29
    sjac(153) = -t35
    sjac(154) = t50
    sjac(155) = 0.25*t118 + t120
    sjac(156) = 0
    sjac(157) = 0.25*t267
    sjac(158) = t316 + t318 - t320
    sjac(159) = -t36 - t37
    sjac(160) = t187
    sjac(161) = t219
    sjac(162) = -t286
    sjac(163) = -t38 - t39
    sjac(164) = t192
    sjac(165) = -t310
    sjac(166) = t332
    sjac(167) = t1
    sjac(168) = t23 + t24
    sjac(169) = -t40 - t41
    sjac(170) = -t51 + t52
    sjac(171) = 0
    sjac(172) = t185 - t186
    sjac(173) = t197
    sjac(174) = t269
    sjac(175) = -t42 - t43
    sjac(176) = 0.02*t58
    sjac(177) = 0.02*t62
    sjac(178) = 0.09*t68
    sjac(179) = t140
    sjac(180) = t220 + t221
    sjac(181) = 0.09*t277 + 0.02*t278 + 0.02*t279
    sjac(182) = -t282
    sjac(183) = -t44 - t45 - t46
    sjac(184) = -t208
    sjac(185) = -t274
    sjac(186) = -t295
    sjac(187) = -t47 - t48 - 2.0*t49
    sjac(188) = t66
    sjac(189) = -t242
    sjac(190) = -t266
    sjac(191) = t312
    sjac(192) = 0.046*t47
    sjac(193) = -t50
    sjac(194) = t67
    sjac(195) = t211
    sjac(196) = 0
    sjac(197) = 0.046*t266
    sjac(198) = -t316
    sjac(199) = t37
    sjac(200) = -t40 + t41
    sjac(201) = -t51 - t53
    sjac(202) = 0
    sjac(203) = t186 + t189
    sjac(204) = t196 + t199 + t200
    sjac(205) = 2.0*t217 + t222 + t223
    sjac(206) = t244 - t247
    sjac(207) = t268 + t269 + t270 + t271 + 2.0*t272
    sjac(208) = t281 + t286 + t287
    sjac(209) = 2.0*t11
    sjac(210) = t34
    sjac(211) = -t54 - t55
    sjac(212) = t76
    sjac(213) = t85
    sjac(214) = t129
    sjac(215) = t133
    sjac(216) = t160
    sjac(217) = t191
    sjac(218) = t200 + t202 + t203 + t204 + t205 + t206 + t207
    sjac(219) = t222
    sjac(220) = t284 - t285
    sjac(221) = -t56 - t57 - t58
    sjac(222) = -t212
    sjac(223) = -t278
    sjac(224) = -t313
    sjac(225) = t19
    sjac(226) = 0.42*t46
    sjac(227) = 0
    sjac(228) = 0.14*t58
    sjac(229) = -t59
    sjac(230) = 0.14*t62
    sjac(231) = 0.33*t65
    sjac(232) = 0.14*t68
    sjac(233) = 1.87*t73 + 1.55*t74 + 2.0*t75 + 2.0*t76
    sjac(234) = 0.22*t82
    sjac(235) = 0.25*t118 + 0.5*t120
    sjac(236) = t127 + t128 + t129
    sjac(237) = t130 + t131 + t132 + t133
    sjac(238) = 0.95*t135 + 0.475*t137 + 0.95*t138
    sjac(239) = 0.23*t153
    sjac(240) = t158
    sjac(241) = 0.475*t179
    sjac(242) = t202 + 2.0*t204 + t205
    sjac(243) = 0
    sjac(244) = 0.95*t257 + 0.25*t267
    sjac(245) = 0.42*t274 + 0.33*t275 + 0.23*t276 + 0.14*t277 + 0.14*t278 + &
        0.14*t279 + 0.22*t280
    sjac(246) = -t289 + t301 + 2.0*t304 + t305 + t321
    sjac(247) = 0.95*t347
    sjac(248) = -t60 - t61 - t62
    sjac(249) = -t214
    sjac(250) = -t279
    sjac(251) = -t314
    sjac(252) = 0.46*t62
    sjac(253) = -t63 - t64 - t65
    sjac(254) = -t209
    sjac(255) = -t275 + 0.46*t279
    sjac(256) = -t296
    sjac(257) = -t66 - t67 - t68
    sjac(258) = -t211
    sjac(259) = -t277
    sjac(260) = -t312
    sjac(261) = t34
    sjac(262) = -t69 - t70 - t71 - t72
    sjac(263) = -t181
    sjac(264) = -t194
    sjac(265) = t207
    sjac(266) = -t239
    sjac(267) = 0
    sjac(268) = -t349
    sjac(269) = -t73 - t74 - t75 - t76
    sjac(270) = 0.16*t112 + 0.16*t114 + 0.16*t115
    sjac(271) = 0.89*t135 + 0.445*t137 + 0.89*t138
    sjac(272) = 0.16*t177 + 0.445*t179
    sjac(273) = -t204
    sjac(274) = 0.89*t257 + 0.16*t258
    sjac(275) = -t304
    sjac(276) = 0.16*t345 + 0.89*t347
    sjac(277) = 0.83*t17
    sjac(278) = -t77 - t78 - t79 - t80
    sjac(279) = -t178
    sjac(280) = -t235
    sjac(281) = -t259
    sjac(282) = 0.83*t299
    sjac(283) = -t346
    sjac(284) = t3
    sjac(285) = t47 + 2.0*t49
    sjac(286) = 0.79*t62
    sjac(287) = 0.65*t68
    sjac(288) = -t81 - t82
    sjac(289) = 0.4*t141 + 0.6*t143 + 0.6*t144 + 0.6*t145
    sjac(290) = 0.6*t184
    sjac(291) = 0.6*t215
    sjac(292) = 0
    sjac(293) = 0.4*t265 + t266
    sjac(294) = 0.65*t277 + 0.79*t279 - t280
    sjac(295) = t315 - t317
    sjac(296) = 0.6*t352
    sjac(297) = 0.806*t77 + 0.806*t79 + 0.806*t80
    sjac(298) = -t83 - t84 - t85
    sjac(299) = 0.7*t112 + 0.7*t114 + 0.7*t115
    sjac(300) = 0.7*t177 + 0.806*t178
    sjac(301) = -t206
    sjac(302) = 0
    sjac(303) = 0.7*t258 + 0.806*t259
    sjac(304) = -t306
    sjac(305) = 0.7*t345 + 0.806*t346
    sjac(306) = t4
    sjac(307) = -t86 - t87 - t88 - t89
    sjac(308) = -t170
    sjac(309) = -t227
    sjac(310) = -t251
    sjac(311) = t293
    sjac(312) = -t338
    sjac(313) = t8
    sjac(314) = -t90 - t91 - t92 - t93
    sjac(315) = -t171
    sjac(316) = -t228
    sjac(317) = -t252
    sjac(318) = t294
    sjac(319) = -t339
    sjac(320) = -t94 - t95 - t96 - t97
    sjac(321) = t151
    sjac(322) = -t174
    sjac(323) = -t231
    sjac(324) = -t255
    sjac(325) = t297
    sjac(326) = -t342
    sjac(327) = 0.025*t18
    sjac(328) = 0.53*t58
    sjac(329) = 0.69*t86 + 0.75*t88 + 0.75*t89
    sjac(330) = 1.06*t90 + 1.39*t92 + 1.39*t93
    sjac(331) = 0.1*t94 + 0.55*t96 + 0.55*t97
    sjac(332) = -t98 - t99
    sjac(333) = 0.8*t146 + t148 + t149 + t150
    sjac(334) = 0.1*t153
    sjac(335) = 0.26*t169 + 0.75*t170 + 1.39*t171 + 0.55*t174 + t183
    sjac(336) = t213
    sjac(337) = 0
    sjac(338) = 0.25*t250 + 0.69*t251 + 1.06*t252 + 0.1*t255 + 0.8*t264
    sjac(339) = 0.1*t276 + 0.53*t278
    sjac(340) = 0.025*t292 - t303
    sjac(341) = 0.25*t328 + 0.26*t330 + 0.26*t331
    sjac(342) = 0.26*t337 + 0.75*t338 + 1.39*t339 + 0.55*t342 + t351
    sjac(343) = 0.8*t353
    sjac(344) = t44
    sjac(345) = -t100 - t101 - t102 - t103
    sjac(346) = -t172
    sjac(347) = 0
    sjac(348) = -t229
    sjac(349) = -t253
    sjac(350) = 0
    sjac(351) = t295
    sjac(352) = -t340
    sjac(353) = t63
    sjac(354) = -t104 - t105 - t106 - t107
    sjac(355) = -t173
    sjac(356) = 0
    sjac(357) = -t230
    sjac(358) = -t254
    sjac(359) = 0
    sjac(360) = t296
    sjac(361) = -t341
    sjac(362) = 0.25*t4
    sjac(363) = 0.75*t8
    sjac(364) = 0.9*t33
    sjac(365) = t38
    sjac(366) = -t108 - t109 - t110 - t111
    sjac(367) = 2.0*t135 + t137 + 2.0*t138
    sjac(368) = t179 - t180
    sjac(369) = 0
    sjac(370) = 0
    sjac(371) = -t238
    sjac(372) = 2.0*t257 - t263
    sjac(373) = 0.25*t293 + 0.75*t294 + 0.9*t300 + t310
    sjac(374) = 2.0*t347 - t348
    sjac(375) = 0.75*t16
    sjac(376) = -t112 - t113 - t114 - t115
    sjac(377) = -t177
    sjac(378) = -t234
    sjac(379) = -t258
    sjac(380) = 0.75*t298
    sjac(381) = -t345
    sjac(382) = t70
    sjac(383) = t78
    sjac(384) = t87
    sjac(385) = t91
    sjac(386) = t95
    sjac(387) = t101
    sjac(388) = t105
    sjac(389) = t108
    sjac(390) = t113
    sjac(391) = -t116 - t117
    sjac(392) = t136
    sjac(393) = t142
    sjac(394) = t147
    sjac(395) = 0
    sjac(396) = t155
    sjac(397) = t162
    sjac(398) = 0
    sjac(399) = 0
    sjac(400) = 0
    sjac(401) = t225 + t226 + t227 + t228 + t229 + t230 + t231 + t232 + t234 &
        + t235 + t236 + t238 + t239 + t240 + t241
    sjac(402) = 0
    sjac(403) = 0
    sjac(404) = -t308
    sjac(405) = t329
    sjac(406) = 0
    sjac(407) = t12
    sjac(408) = t28
    sjac(409) = 0.1*t68
    sjac(410) = t81
    sjac(411) = -t118 - t119 - 2.0*t120 - t121
    sjac(412) = 0
    sjac(413) = 0
    sjac(414) = -t195
    sjac(415) = 0
    sjac(416) = -t243
    sjac(417) = -t267
    sjac(418) = 0.1*t277
    sjac(419) = t317 + t319
    sjac(420) = 0
    sjac(421) = t45
    sjac(422) = t57
    sjac(423) = t61
    sjac(424) = t64
    sjac(425) = -t122 - t123 - t124 - t125 - 2.0*t126
    sjac(426) = t152
    sjac(427) = -t182
    sjac(428) = t208 + t209 + t210 + t212 + t214
    sjac(429) = -t237
    sjac(430) = -t262
    sjac(431) = 0
    sjac(432) = 0
    sjac(433) = -t350
    sjac(434) = t35
    sjac(435) = 0
    sjac(436) = 0
    sjac(437) = 0.45*t77 + 0.45*t79 + 0.45*t80
    sjac(438) = 0.9*t82
    sjac(439) = 0.17*t112 + 0.17*t114 + 0.17*t115
    sjac(440) = 0.5*t118 + t120
    sjac(441) = -t127 - t128 - t129
    sjac(442) = 0.11*t135 + 0.055*t137 + 0.11*t138
    sjac(443) = 0
    sjac(444) = t154 + 0.75*t156 + t157
    sjac(445) = 0.75*t175 + 0.17*t177 + 0.45*t178 + 0.055*t179
    sjac(446) = 0
    sjac(447) = -t205
    sjac(448) = 0
    sjac(449) = 0.11*t257 + 0.17*t258 + 0.45*t259 + t261 + 0.5*t267
    sjac(450) = 0.9*t280
    sjac(451) = -t305 + t320
    sjac(452) = t343 + 0.17*t345 + 0.45*t346 + 0.11*t347
    sjac(453) = 0.009*t18
    sjac(454) = t19
    sjac(455) = t30 + 0.5*t31
    sjac(456) = t38
    sjac(457) = t46
    sjac(458) = t47 + t49
    sjac(459) = 0
    sjac(460) = 0.04*t62
    sjac(461) = 0.53*t65
    sjac(462) = 0.58*t68
    sjac(463) = t71
    sjac(464) = 0.13*t73 + 0.45*t74
    sjac(465) = t79
    sjac(466) = 0.77*t88
    sjac(467) = 0.04*t90 + 0.8*t92
    sjac(468) = 0.28*t94 + 0.89*t96 + 0.14*t97
    sjac(469) = 1.6*t100 + 1.55*t102 + 0.8*t103
    sjac(470) = t104 + 1.25*t106 + 0.5*t107
    sjac(471) = t109
    sjac(472) = t114
    sjac(473) = 0.75*t118 + 0.5*t120
    sjac(474) = t122 + 1.75*t124 + t125 + 2.0*t126
    sjac(475) = -t130 - t131 - t132 - t133
    sjac(476) = 0.5*t137
    sjac(477) = 0.25*t141 + 1.4*t143 + 0.4*t144 + 0.4*t145
    sjac(478) = t148
    sjac(479) = 0.18*t153
    sjac(480) = 0.75*t156
    sjac(481) = 0.75*t163
    sjac(482) = t165 + 1.5*t167 + 0.75*t168 + 0.84*t169 + 0.77*t170 + &
        0.8*t171 + 1.55*t172 + 1.25*t173 + 0.89*t174 + 0.75*t175 + t176 + &
        t177 + t178 + 0.5*t179 + t180 + t181 + 1.75*t182 + t183 + 1.4*t184
    sjac(483) = 0
    sjac(484) = -t202 + 0.4*t215
    sjac(485) = 0
    sjac(486) = t249 + 0.09*t250 + 0.04*t252 + 1.6*t253 + t254 + 0.28*t255 + &
        t262 + 0.25*t265 + t266 + 0.75*t267
    sjac(487) = t274 + 0.53*t275 + 0.18*t276 + 0.58*t277 + 0.04*t279
    sjac(488) = 0.009*t292 - t301 + 0.5*t307 + t310 + t321
    sjac(489) = 0.09*t328 + 0.84*t330
    sjac(490) = t335 + 0.8*t340 + 0.5*t341 + 0.14*t342 + t350 + 0.4*t352
    sjac(491) = t5
    sjac(492) = 0.9*t33
    sjac(493) = t83 + t84 + t85
    sjac(494) = 0
    sjac(495) = -t134 - t135 - t136 - t137 - t138
    sjac(496) = -t179
    sjac(497) = -t193
    sjac(498) = t206
    sjac(499) = -t236
    sjac(500) = -t257
    sjac(501) = 0.9*t300 + t306
    sjac(502) = -t347
    sjac(503) = t2
    sjac(504) = t4
    sjac(505) = t8
    sjac(506) = t18
    sjac(507) = -t25
    sjac(508) = t27
    sjac(509) = t32
    sjac(510) = t37
    sjac(511) = t43
    sjac(512) = 0
    sjac(513) = t55
    sjac(514) = 0
    sjac(515) = 0
    sjac(516) = 0
    sjac(517) = 0
    sjac(518) = t75
    sjac(519) = t84
    sjac(520) = t99
    sjac(521) = 0
    sjac(522) = t128
    sjac(523) = t132
    sjac(524) = 0
    sjac(525) = -t139
    sjac(526) = 0
    sjac(527) = 0
    sjac(528) = 0
    sjac(529) = 0
    sjac(530) = t159
    sjac(531) = 0
    sjac(532) = 0
    sjac(533) = 0
    sjac(534) = 0
    sjac(535) = t223
    sjac(536) = 0
    sjac(537) = 0
    sjac(538) = t282 + t285 + t286 + t287 + t290 + t291 + t292 + t293 + t294 &
        + t301 + t302 + t303 + t304 + t305 + t306 + t309
    sjac(539) = 0
    sjac(540) = 0
    sjac(541) = 0
    sjac(542) = t60
    sjac(543) = -t141 - t142 - t143 - t144 - t145
    sjac(544) = -t184
    sjac(545) = -t215
    sjac(546) = -t241
    sjac(547) = -t265
    sjac(548) = 0
    sjac(549) = t314
    sjac(550) = -t352
    sjac(551) = t56
    sjac(552) = -t146 - t147 - t148 - t149 - t150
    sjac(553) = -t183
    sjac(554) = -t213
    sjac(555) = -t240
    sjac(556) = -t264
    sjac(557) = 0
    sjac(558) = t313
    sjac(559) = -t351
    sjac(560) = 0.25*t141 + 0.4*t143 + 0.4*t144 + 0.4*t145
    sjac(561) = -t151 - t152 - t153
    sjac(562) = 0.4*t184
    sjac(563) = -t210 + 0.4*t215
    sjac(564) = 0
    sjac(565) = 0.25*t265
    sjac(566) = -t276
    sjac(567) = -t297
    sjac(568) = 0.4*t352
    sjac(569) = 0.42*t58
    sjac(570) = 0.42*t62
    sjac(571) = t99
    sjac(572) = 0
    sjac(573) = 0
    sjac(574) = -t154 - t155 - t156 - t157
    sjac(575) = -t175
    sjac(576) = 0
    sjac(577) = -t232
    sjac(578) = -t261
    sjac(579) = 0.42*t278 + 0.42*t279
    sjac(580) = t303
    sjac(581) = 0
    sjac(582) = -t343
    sjac(583) = 0
    sjac(584) = 0.075*t18
    sjac(585) = 0.65*t58
    sjac(586) = 0.5*t65
    sjac(587) = 0.38*t86 + 0.41*t88 + 0.41*t89
    sjac(588) = 0.35*t90 + 0.46*t92 + 0.46*t93
    sjac(589) = 1.45*t94 + 0.725*t96 + 0.725*t97
    sjac(590) = 0.2*t100 + 0.35*t102 + 0.6*t103
    sjac(591) = t104 + 0.75*t106 + t107
    sjac(592) = t116 + 0.5*t117
    sjac(593) = t122 + t124 + t125 + 2.0*t126
    sjac(594) = 0
    sjac(595) = 0
    sjac(596) = 0.8*t146 + t148 + t149 + t150
    sjac(597) = 0.72*t153
    sjac(598) = 0
    sjac(599) = -t158 - t159 - t160
    sjac(600) = t161 + 0.75*t163 + t164
    sjac(601) = 0.75*t168 + 0.77*t169 + 0.41*t170 + 0.46*t171 + 0.35*t172 + &
        0.75*t173 + 0.725*t174 + t182 + t183
    sjac(602) = 0
    sjac(603) = -t203 + t213
    sjac(604) = 0
    sjac(605) = 0.75*t250 + 0.38*t251 + 0.35*t252 + 0.2*t253 + t254 + &
        1.45*t255 + t260 + t262 + 0.8*t264
    sjac(606) = 0.5*t275 + 0.72*t276 + 0.65*t278
    sjac(607) = 0.075*t292 - t302 + 0.5*t308
    sjac(608) = 0.75*t328 + 0.77*t330 + 0.77*t331
    sjac(609) = t336 + 0.77*t337 + 0.41*t338 + 0.46*t339 + 0.6*t340 + t341 + &
        0.725*t342 + t350 + t351
    sjac(610) = 0.2*t353
    sjac(611) = t2
    sjac(612) = 0.2*t58
    sjac(613) = 0.16*t62
    sjac(614) = t98
    sjac(615) = 0
    sjac(616) = 0
    sjac(617) = -t161 - t162 - t163 - t164
    sjac(618) = -t168
    sjac(619) = 0
    sjac(620) = -t225
    sjac(621) = -t260
    sjac(622) = 0.2*t278 + 0.16*t279
    sjac(623) = t291
    sjac(624) = 0
    sjac(625) = -t336
    sjac(626) = 0
    sjac(627) = t26
    sjac(628) = 0.5*t31
    sjac(629) = t32
    sjac(630) = 0.22*t65
    sjac(631) = 0.08*t68
    sjac(632) = -t71 + t72
    sjac(633) = -t79 + t80
    sjac(634) = -t88 + 0.5*t89
    sjac(635) = -t92 + 0.5*t93
    sjac(636) = -t96 + 0.5*t97
    sjac(637) = -t102 + 0.5*t103
    sjac(638) = -t106 + 0.5*t107
    sjac(639) = -t109 + t110
    sjac(640) = -t114 + t115
    sjac(641) = -t124 + 0.5*t125
    sjac(642) = -t137 + t138
    sjac(643) = -t143 + t144
    sjac(644) = -t148 + t149
    sjac(645) = 0.31*t153
    sjac(646) = -t156 + 0.5*t157
    sjac(647) = t158
    sjac(648) = -t163 + 0.5*t164
    sjac(649) = -t165 - t166 - 2.0*t167 - t168 - t169 - t170 - t171 - t172 - &
        t173 - t174 - t175 - 0.5*t176 - t177 - t178 - t179 - t180 - t181 - &
        t182 - t183 - t184
    sjac(650) = 0
    sjac(651) = 0
    sjac(652) = -t224
    sjac(653) = -t249 + t256
    sjac(654) = 0.22*t275 + 0.31*t276 + 0.08*t277
    sjac(655) = t290 + 0.5*t307
    sjac(656) = -t330 + 0.5*t331
    sjac(657) = t333 - 0.5*t335 + 0.5*t336 + 0.5*t337 + 0.5*t338 + 0.5*t339 + &
        0.5*t340 + 0.5*t341 + 0.5*t342 + 0.5*t343 + 2.0*t344 + t345 + t346 + &
        t347 + t348 + t349 + 0.5*t350 + t351 + t352
    sjac(658) = 0
    sjac(659) = t5
    sjac(660) = t10
    sjac(661) = t19
    sjac(662) = t28 + t29
    sjac(663) = t36 + t37
    sjac(664) = t39
    sjac(665) = -t41
    sjac(666) = t47
    sjac(667) = 0
    sjac(668) = 2.0*t53
    sjac(669) = t54
    sjac(670) = 0
    sjac(671) = -t69
    sjac(672) = 0
    sjac(673) = t77
    sjac(674) = 0
    sjac(675) = 0.92*t86
    sjac(676) = 0.76*t90
    sjac(677) = t94
    sjac(678) = t100
    sjac(679) = t104
    sjac(680) = t111
    sjac(681) = t112
    sjac(682) = t118 - t121
    sjac(683) = 2.0*t122 + t124 + t125 + 2.0*t126
    sjac(684) = 0
    sjac(685) = 0
    sjac(686) = -t134 + t135
    sjac(687) = 0
    sjac(688) = 0.65*t141 + t145
    sjac(689) = 0.8*t146 + t150
    sjac(690) = 0
    sjac(691) = t154
    sjac(692) = 0
    sjac(693) = t161
    sjac(694) = t165 + t182
    sjac(695) = -t185 - t186 - t187 - t188 - t190 - t191 - t192 - t193 - t194 &
        - t195
    sjac(696) = t197 + 2.0*t198 - t201 + t213 + t215
    sjac(697) = t218 - t219
    sjac(698) = t244 + t245 + 2.0*t247 + 2.0*t248 + t249 + 0.964*t250 + &
        0.92*t251 + 0.76*t252 + t253 + t254 + t255 + t256 + t257 + t258 + &
        t259 + t260 + t261 + 2.0*t262 + t263 + 0.8*t264 + 0.65*t265 + t266 + &
        t267
    sjac(699) = t270 - t273
    sjac(700) = -t284 + t286 + t311 + t318 + t321
    sjac(701) = 0.964*t328
    sjac(702) = -t332 + t333 + t350
    sjac(703) = t353 + t354
    sjac(704) = t10
    sjac(705) = -t13
    sjac(706) = -t34
    sjac(707) = t38
    sjac(708) = -t45
    sjac(709) = t55
    sjac(710) = -t57
    sjac(711) = -t61
    sjac(712) = -t64
    sjac(713) = -t67
    sjac(714) = -t76
    sjac(715) = -t85
    sjac(716) = 0
    sjac(717) = -t129
    sjac(718) = -t133
    sjac(719) = 0
    sjac(720) = -t145
    sjac(721) = -t150
    sjac(722) = -t152
    sjac(723) = 0
    sjac(724) = -t160
    sjac(725) = 0
    sjac(726) = 0
    sjac(727) = t188 - t189 - t190
    sjac(728) = -t196 - t197 - t198 - t199 - t200 - t201 - t202 - t203 - t204 &
        - t205 - t206 - t207 - t208 - t209 - t210 - t211 - t212 - t213 - t214 &
        - t215 - t216
    sjac(729) = -t222
    sjac(730) = -t248
    sjac(731) = t273
    sjac(732) = t285 + t310
    sjac(733) = 0
    sjac(734) = 0
    sjac(735) = 0
    sjac(736) = t9
    sjac(737) = 0
    sjac(738) = 0.25*t16
    sjac(739) = 0.17*t17
    sjac(740) = 0.17*t18
    sjac(741) = t30
    sjac(742) = 0.1*t33
    sjac(743) = t35
    sjac(744) = t36
    sjac(745) = t43
    sjac(746) = 0.12*t46
    sjac(747) = t47 - t48 + t49
    sjac(748) = 0
    sjac(749) = 0.1*t58
    sjac(750) = t59
    sjac(751) = 0.1*t62
    sjac(752) = 0.23*t65
    sjac(753) = 0.25*t68
    sjac(754) = -t70 + t71
    sjac(755) = 0.8*t74 + t75 + t76
    sjac(756) = t77 - t78 + 2.0*t79 + t80
    sjac(757) = 0.32*t82
    sjac(758) = 0.98*t83
    sjac(759) = 0.92*t86 - t87 + t88 + 0.5*t89
    sjac(760) = 0.76*t90 - t91 + t92 + 0.5*t93
    sjac(761) = t94 - t95 + t96 + 0.5*t97
    sjac(762) = t100 - t101 + t102 + 0.5*t103
    sjac(763) = t104 - t105 + t106 + 0.5*t107
    sjac(764) = -t108 + t109
    sjac(765) = t112 - t113 + 2.0*t114 + t115
    sjac(766) = t116
    sjac(767) = 0.75*t118 - t119 + t120
    sjac(768) = -t123 + 0.5*t124
    sjac(769) = t127
    sjac(770) = 2.0*t131 + t132 + t133
    sjac(771) = 0.92*t135 - t136 + 0.46*t137 + 0.92*t138
    sjac(772) = -2.0*t140
    sjac(773) = 0.65*t141 - t142 + 2.0*t143 + t144 + t145
    sjac(774) = 0.8*t146 - t147 + 2.0*t148 + t149 + t150
    sjac(775) = 0.26*t153
    sjac(776) = t154 - t155 + t156 + 0.5*t157
    sjac(777) = t158
    sjac(778) = t161 - t162 + t163 + 0.5*t164
    sjac(779) = t165 - t166 + t167 + t168 + t169 + t170 + t171 + t172 + t173 &
        + t174 + t175 + 0.5*t176 + 2.0*t177 + 2.0*t178 + 0.46*t179 + t180 + &
        t181 + 0.5*t182 + 2.0*t183 + 2.0*t184
    sjac(780) = -t187
    sjac(781) = -t200 + t202 + t204 + t213 + t215
    sjac(782) = -t217 - t218 - t219 - 2.0*t220 - 2.0*t221 - t222 - t223 - &
        t224 - t225 - t226 - t227 - t228 - t229 - t230 - t231 - t232 - t233 - &
        t234 - t235 - t236 - t237 - t238 - t239 - t240 - t241 - t242 - t243
    sjac(783) = -t245 + t249 + 0.964*t250 + 0.92*t251 + 0.76*t252 + t253 + &
        t254 + t255 + 0.92*t257 + t258 + t259 + t260 + t261 + 0.8*t264 + &
        0.65*t265 + t266 + 0.75*t267
    sjac(784) = t271 - t272 + 0.12*t274 + 0.23*t275 + 0.26*t276 + 0.25*t277 + &
        0.1*t278 + 0.1*t279 + 0.32*t280
    sjac(785) = t281 + t282 - t287 + t288 + t289 + 0.17*t292 + 0.25*t298 + &
        0.17*t299 + 0.1*t300 + t301 + t304 + t320
    sjac(786) = 0.964*t328 - t329 + t330 + 0.5*t331
    sjac(787) = -t334 + 0.5*t335 + 0.5*t336 + 0.5*t337 + 0.5*t338 + 0.5*t339 &
        + 0.5*t340 + 0.5*t341 + 0.5*t342 + 0.5*t343 + t345 + t346 + 0.92*t347 &
        + t351 + t352
    sjac(788) = t353
    sjac(789) = t6
    sjac(790) = t41
    sjac(791) = -t47
    sjac(792) = -2.0*t53
    sjac(793) = 0
    sjac(794) = -t77
    sjac(795) = -t86
    sjac(796) = -t90
    sjac(797) = -t94
    sjac(798) = -t100
    sjac(799) = -t104
    sjac(800) = -t111
    sjac(801) = -t112
    sjac(802) = -t118
    sjac(803) = -t122
    sjac(804) = -t135
    sjac(805) = 0
    sjac(806) = -t141
    sjac(807) = -t146
    sjac(808) = 0
    sjac(809) = -t154
    sjac(810) = 0
    sjac(811) = -t161
    sjac(812) = -t165
    sjac(813) = t185 + t186 + t189
    sjac(814) = t196 - t198 + t199
    sjac(815) = -t218
    sjac(816) = -t244 - t245 - t246 - 2.0*t247 - t248 - t249 - t250 - t251 - &
        t252 - t253 - t254 - t255 - t256 - t257 - t258 - t259 - t260 - t261 - &
        t262 - t263 - t264 - t265 - t266 - t267
    sjac(817) = -t270
    sjac(818) = -t283
    sjac(819) = -t328
    sjac(820) = -t333
    sjac(821) = 0
    sjac(822) = t40
    sjac(823) = -t46
    sjac(824) = t51
    sjac(825) = -t58
    sjac(826) = -t62
    sjac(827) = -t65
    sjac(828) = -t68
    sjac(829) = -t82
    sjac(830) = 0
    sjac(831) = 0
    sjac(832) = 0
    sjac(833) = -t153
    sjac(834) = 0
    sjac(835) = 0
    sjac(836) = 0
    sjac(837) = 0
    sjac(838) = -t188
    sjac(839) = 0
    sjac(840) = -t217
    sjac(841) = -t244
    sjac(842) = -t268 - t269 - t270 - t271 - t272 - t273 - t274 - t275 - t276 &
        - t277 - t278 - t279 - t280
    sjac(843) = -t281
    sjac(844) = 0
    sjac(845) = 0
    sjac(846) = 0
    sjac(847) = -t2
    sjac(848) = -t4
    sjac(849) = t6
    sjac(850) = -t7
    sjac(851) = -t8
    sjac(852) = -t9
    sjac(853) = -t12
    sjac(854) = -t14 - t15
    sjac(855) = -t16
    sjac(856) = -t17
    sjac(857) = -t18
    sjac(858) = -t19
    sjac(859) = -t20
    sjac(860) = -t21
    sjac(861) = -t22
    sjac(862) = 2.0*t25
    sjac(863) = t26 - t27
    sjac(864) = -t29
    sjac(865) = t30 - 0.5*t31
    sjac(866) = -t32
    sjac(867) = -1.9*t33
    sjac(868) = -t35
    sjac(869) = -t37
    sjac(870) = -t38
    sjac(871) = 2.0*t42 - t43
    sjac(872) = -t44
    sjac(873) = -t50
    sjac(874) = 0
    sjac(875) = t54 - t55
    sjac(876) = -t56 + 0.85*t58
    sjac(877) = -t59
    sjac(878) = -t60 + 0.85*t62
    sjac(879) = -t63 + 0.1*t65
    sjac(880) = -t66 + 0.25*t68
    sjac(881) = -t75
    sjac(882) = -t81 + 0.19*t82
    sjac(883) = -t84
    sjac(884) = -t99
    sjac(885) = 0
    sjac(886) = t116 - 0.5*t117
    sjac(887) = 0
    sjac(888) = -t128
    sjac(889) = -t132
    sjac(890) = 0
    sjac(891) = 2.0*t139
    sjac(892) = 0
    sjac(893) = 0
    sjac(894) = -t151 + 0.14*t153
    sjac(895) = 0
    sjac(896) = -t159
    sjac(897) = 0
    sjac(898) = 0
    sjac(899) = -t191
    sjac(900) = 0
    sjac(901) = t217 + t218 - t223
    sjac(902) = t245 - t246
    sjac(903) = -t271 + t272 + 0.1*t275 + 0.14*t276 + 0.25*t277 + 0.85*t278 + &
        0.85*t279 + 0.19*t280
    sjac(904) = -t281 - t282 - t283 - t284 - t285 - t286 - t287 - t288 - t289 &
        - t290 - t291 - t292 - t293 - t294 - t295 - t296 - t297 - t298 - t299 &
        - 1.9*t300 - t301 - t302 - t303 - t304 - t305 - t306 - 0.5*t307 - &
        0.5*t308 - t309 - t310 - t311 - t312 - t313 - t314 - t316 - t317 - &
        t318 - t319 - t320 - t321 - t322 - t323 - t324 - t325 - t326 - t327
    sjac(905) = 0
    sjac(906) = 0
    sjac(907) = -t354
    sjac(908) = 0.83*t18
    sjac(909) = 0.5*t117
    sjac(910) = 0
    sjac(911) = 0
    sjac(912) = 0
    sjac(913) = 0
    sjac(914) = 0
    sjac(915) = 0
    sjac(916) = -t169
    sjac(917) = 0
    sjac(918) = 0
    sjac(919) = -t226
    sjac(920) = -t250
    sjac(921) = 0
    sjac(922) = 0.83*t292 + 0.5*t308 + t311
    sjac(923) = -t328 - t329 - t330 - t331
    sjac(924) = -t337
    sjac(925) = t354
    sjac(926) = t27
    sjac(927) = t39
    sjac(928) = 0.1*t68
    sjac(929) = -t72
    sjac(930) = -t80
    sjac(931) = 0.1*t82
    sjac(932) = 0.02*t83
    sjac(933) = -t89
    sjac(934) = -t93
    sjac(935) = -t97
    sjac(936) = t98
    sjac(937) = -t103
    sjac(938) = -t107
    sjac(939) = -t110
    sjac(940) = -t115
    sjac(941) = 0.25*t118
    sjac(942) = -t125
    sjac(943) = t127 + t128 + t129
    sjac(944) = 0.05*t135 + 0.03*t137 - 0.95*t138
    sjac(945) = -t144
    sjac(946) = -t149
    sjac(947) = 0
    sjac(948) = -t157
    sjac(949) = t159 + t160
    sjac(950) = -t164
    sjac(951) = -t176 + 0.03*t179
    sjac(952) = -t192
    sjac(953) = t203 + t205
    sjac(954) = -t233
    sjac(955) = -t256 + 0.05*t257 + 0.25*t267
    sjac(956) = 0.1*t277 + 0.1*t280
    sjac(957) = t302 + t305 + t309
    sjac(958) = -t331
    sjac(959) = -t332 - t333 - t334 - t335 - t336 - t337 - t338 - t339 - t340 &
        - t341 - t342 - t343 - 2.0*t344 - t345 - t346 - 0.95*t347 - t348 - &
        t349 - t350 - t351 - t352
    sjac(960) = 0
    sjac(961) = t69
    sjac(962) = 0.08*t86
    sjac(963) = 0.24*t90
    sjac(964) = t123
    sjac(965) = 0.35*t141
    sjac(966) = 0.2*t146
    sjac(967) = 0
    sjac(968) = 0
    sjac(969) = t194
    sjac(970) = 0
    sjac(971) = t237
    sjac(972) = 0.036*t250 + 0.08*t251 + 0.24*t252 + 0.2*t264 + 0.35*t265
    sjac(973) = 0
    sjac(974) = -t311
    sjac(975) = 0.036*t328
    sjac(976) = 0
    sjac(977) = -t353 - t354
  END SUBROUTINE Jac



END MODULE kppa_Serial_jacobian
!---------------------- END kppa_Serial_jacobian.f90 END ---------------------
