! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_Parameters.f90
! Time                 : Tue Mar 10 15:23:26 2015
! Working directory    : /users/charlesj/KPP_BOXMODEL/cosmo-art-new/kpp-2.2.3_files_with_Prace_Integrator
! Equation file        : kpp.kpp
! Output root filename : kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kpp_Parameters

  USE kpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 83 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 83 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 77 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 194 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 84 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 835 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 977 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 84 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_NH3 = 1 
  INTEGER, PARAMETER :: ind_N2 = 2 
  INTEGER, PARAMETER :: ind_SULF = 3 
  INTEGER, PARAMETER :: ind_ORA1 = 4 
  INTEGER, PARAMETER :: ind_ORA2 = 5 
  INTEGER, PARAMETER :: ind_CS1 = 6 
  INTEGER, PARAMETER :: ind_CO2 = 7 
  INTEGER, PARAMETER :: ind_H2 = 8 
  INTEGER, PARAMETER :: ind_ETH = 9 
  INTEGER, PARAMETER :: ind_ISHP = 10 
  INTEGER, PARAMETER :: ind_HC5 = 11 
  INTEGER, PARAMETER :: ind_TPAN = 12 
  INTEGER, PARAMETER :: ind_HONO = 13 
  INTEGER, PARAMETER :: ind_DMSO = 14 
  INTEGER, PARAMETER :: ind_HC8 = 15 
  INTEGER, PARAMETER :: ind_SO2 = 16 
  INTEGER, PARAMETER :: ind_N2O5 = 17 
  INTEGER, PARAMETER :: ind_MAHP = 18 
  INTEGER, PARAMETER :: ind_DMS = 19 
  INTEGER, PARAMETER :: ind_TOL = 20 
  INTEGER, PARAMETER :: ind_XYL = 21 
  INTEGER, PARAMETER :: ind_HC3 = 22 
  INTEGER, PARAMETER :: ind_NALD = 23 
  INTEGER, PARAMETER :: ind_CS10 = 24 
  INTEGER, PARAMETER :: ind_CS100 = 25 
  INTEGER, PARAMETER :: ind_CS1000 = 26 
  INTEGER, PARAMETER :: ind_O1D = 27 
  INTEGER, PARAMETER :: ind_PAA = 28 
  INTEGER, PARAMETER :: ind_MPAN = 29 
  INTEGER, PARAMETER :: ind_OP1 = 30 
  INTEGER, PARAMETER :: ind_CH4 = 31 
  INTEGER, PARAMETER :: ind_CSL = 32 
  INTEGER, PARAMETER :: ind_HACE = 33 
  INTEGER, PARAMETER :: ind_HNO4 = 34 
  INTEGER, PARAMETER :: ind_PAN = 35 
  INTEGER, PARAMETER :: ind_O3P = 36 
  INTEGER, PARAMETER :: ind_H2O2 = 37 
  INTEGER, PARAMETER :: ind_OL2 = 38 
  INTEGER, PARAMETER :: ind_ISOP = 39 
  INTEGER, PARAMETER :: ind_ISON = 40 
  INTEGER, PARAMETER :: ind_O2 = 41 
  INTEGER, PARAMETER :: ind_HNO3 = 42 
  INTEGER, PARAMETER :: ind_API = 43 
  INTEGER, PARAMETER :: ind_CO = 44 
  INTEGER, PARAMETER :: ind_LIM = 45 
  INTEGER, PARAMETER :: ind_OLT = 46 
  INTEGER, PARAMETER :: ind_ISO = 47 
  INTEGER, PARAMETER :: ind_XNO2 = 48 
  INTEGER, PARAMETER :: ind_GLY = 49 
  INTEGER, PARAMETER :: ind_XYLP = 50 
  INTEGER, PARAMETER :: ind_MACR = 51 
  INTEGER, PARAMETER :: ind_DCB = 52 
  INTEGER, PARAMETER :: ind_HC5P = 53 
  INTEGER, PARAMETER :: ind_HC8P = 54 
  INTEGER, PARAMETER :: ind_OLIP = 55 
  INTEGER, PARAMETER :: ind_KET = 56 
  INTEGER, PARAMETER :: ind_OL2P = 57 
  INTEGER, PARAMETER :: ind_OLTP = 58 
  INTEGER, PARAMETER :: ind_XO2 = 59 
  INTEGER, PARAMETER :: ind_TOLP = 60 
  INTEGER, PARAMETER :: ind_OP2 = 61 
  INTEGER, PARAMETER :: ind_MACP = 62 
  INTEGER, PARAMETER :: ind_OLN = 63 
  INTEGER, PARAMETER :: ind_MGLY = 64 
  INTEGER, PARAMETER :: ind_HCHO = 65 
  INTEGER, PARAMETER :: ind_TCO3 = 66 
  INTEGER, PARAMETER :: ind_H2O = 67 
  INTEGER, PARAMETER :: ind_LIMP = 68 
  INTEGER, PARAMETER :: ind_APIP = 69 
  INTEGER, PARAMETER :: ind_OLI = 70 
  INTEGER, PARAMETER :: ind_KETP = 71 
  INTEGER, PARAMETER :: ind_ALD = 72 
  INTEGER, PARAMETER :: ind_ETHP = 73 
  INTEGER, PARAMETER :: ind_MO2 = 74 
  INTEGER, PARAMETER :: ind_NO2 = 75 
  INTEGER, PARAMETER :: ind_NO3 = 76 
  INTEGER, PARAMETER :: ind_HO2 = 77 
  INTEGER, PARAMETER :: ind_NO = 78 
  INTEGER, PARAMETER :: ind_O3 = 79 
  INTEGER, PARAMETER :: ind_HO = 80 
  INTEGER, PARAMETER :: ind_HC3P = 81 
  INTEGER, PARAMETER :: ind_ACO3 = 82 
  INTEGER, PARAMETER :: ind_ONIT = 83 

! Index declaration for fixed species in C
!   C(ind_spc)


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)


END MODULE kpp_Parameters

