!------------------- BEGIN kppa_OpenMP_initialize.f90 BEGIN ------------------
! @file kppa_OpenMP_initialize.f90                                            
! @author charlesj                                                            
! @date 2014-12-18 14:51:39.374291                                            
! @brief Species concentration initialization                                 
!                                                                             
! Species concentration initialization                                        
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE kppa_OpenMP_initialize

  USE kppa_OpenMP_parameters

  IMPLICIT NONE





  CONTAINS

!--------------------------------- Initialize --------------------------------
! Species concentration initialization.                                       
! Concentrations are usually supplied by the model from input data            
! or other calculations, not specified directly as done here.                 
!                                                                             
! @param[in,out] var Variable species concentrations                          
! @param[in,out] fix Fixed species concentrations                             
!-----------------------------------------------------------------------------
  SUBROUTINE Initialize(var, fix)
    IMPLICIT NONE

    REAL(8), INTENT(INOUT) :: var(83)
    REAL(8), INTENT(INOUT) :: fix(0)

    ! Variable species initialization 
    var(1) = CFACTOR*VAR_DEFAULT
    var(2) = CFACTOR*VAR_DEFAULT
    var(3) = CFACTOR*VAR_DEFAULT
    var(4) = CFACTOR*VAR_DEFAULT
    var(5) = CFACTOR*VAR_DEFAULT
    var(6) = CFACTOR*VAR_DEFAULT
    var(7) = CFACTOR*VAR_DEFAULT
    var(8) = CFACTOR*VAR_DEFAULT
    var(9) = CFACTOR*VAR_DEFAULT
    var(10) = CFACTOR*VAR_DEFAULT
    var(11) = CFACTOR*VAR_DEFAULT
    var(12) = CFACTOR*VAR_DEFAULT
    var(13) = CFACTOR*VAR_DEFAULT
    var(14) = CFACTOR*VAR_DEFAULT
    var(15) = CFACTOR*VAR_DEFAULT
    var(16) = CFACTOR*VAR_DEFAULT
    var(17) = CFACTOR*VAR_DEFAULT
    var(18) = CFACTOR*VAR_DEFAULT
    var(19) = CFACTOR*VAR_DEFAULT
    var(20) = CFACTOR*VAR_DEFAULT
    var(21) = CFACTOR*VAR_DEFAULT
    var(22) = CFACTOR*VAR_DEFAULT
    var(23) = CFACTOR*VAR_DEFAULT
    var(24) = CFACTOR*VAR_DEFAULT
    var(25) = CFACTOR*VAR_DEFAULT
    var(26) = CFACTOR*VAR_DEFAULT
    var(27) = CFACTOR*VAR_DEFAULT
    var(28) = CFACTOR*VAR_DEFAULT
    var(29) = CFACTOR*VAR_DEFAULT
    var(30) = CFACTOR*VAR_DEFAULT
    var(31) = CFACTOR*VAR_DEFAULT
    var(32) = CFACTOR*VAR_DEFAULT
    var(33) = CFACTOR*VAR_DEFAULT
    var(34) = CFACTOR*VAR_DEFAULT
    var(35) = CFACTOR*VAR_DEFAULT
    var(36) = CFACTOR*VAR_DEFAULT
    var(37) = CFACTOR*VAR_DEFAULT
    var(38) = CFACTOR*VAR_DEFAULT
    var(39) = CFACTOR*VAR_DEFAULT
    var(40) = CFACTOR*VAR_DEFAULT
    var(41) = CFACTOR*VAR_DEFAULT
    var(42) = CFACTOR*VAR_DEFAULT
    var(43) = CFACTOR*VAR_DEFAULT
    var(44) = CFACTOR*VAR_DEFAULT
    var(45) = CFACTOR*VAR_DEFAULT
    var(46) = CFACTOR*VAR_DEFAULT
    var(47) = CFACTOR*VAR_DEFAULT
    var(48) = CFACTOR*VAR_DEFAULT
    var(49) = CFACTOR*VAR_DEFAULT
    var(50) = CFACTOR*VAR_DEFAULT
    var(51) = CFACTOR*VAR_DEFAULT
    var(52) = CFACTOR*VAR_DEFAULT
    var(53) = CFACTOR*VAR_DEFAULT
    var(54) = CFACTOR*VAR_DEFAULT
    var(55) = CFACTOR*VAR_DEFAULT
    var(56) = CFACTOR*VAR_DEFAULT
    var(57) = CFACTOR*VAR_DEFAULT
    var(58) = CFACTOR*VAR_DEFAULT
    var(59) = CFACTOR*VAR_DEFAULT
    var(60) = CFACTOR*VAR_DEFAULT
    var(61) = CFACTOR*VAR_DEFAULT
    var(62) = CFACTOR*VAR_DEFAULT
    var(63) = CFACTOR*VAR_DEFAULT
    var(64) = CFACTOR*VAR_DEFAULT
    var(65) = CFACTOR*VAR_DEFAULT
    var(66) = CFACTOR*VAR_DEFAULT
    var(67) = CFACTOR*VAR_DEFAULT
    var(68) = CFACTOR*VAR_DEFAULT
    var(69) = CFACTOR*VAR_DEFAULT
    var(70) = CFACTOR*VAR_DEFAULT
    var(71) = CFACTOR*VAR_DEFAULT
    var(72) = CFACTOR*VAR_DEFAULT
    var(73) = CFACTOR*VAR_DEFAULT
    var(74) = CFACTOR*VAR_DEFAULT
    var(75) = CFACTOR*VAR_DEFAULT
    var(76) = CFACTOR*VAR_DEFAULT
    var(77) = CFACTOR*VAR_DEFAULT
    var(78) = CFACTOR*VAR_DEFAULT
    var(79) = CFACTOR*VAR_DEFAULT
    var(80) = CFACTOR*VAR_DEFAULT
    var(81) = CFACTOR*VAR_DEFAULT
    var(82) = CFACTOR*VAR_DEFAULT
    var(83) = CFACTOR*VAR_DEFAULT

    ! Fixed species initialization 
  END SUBROUTINE Initialize


END MODULE kppa_OpenMP_initialize
!--------------------- END kppa_OpenMP_initialize.f90 END --------------------
