! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Main Program File
! 
! Generated by KPP-2.2.1_rs5 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_Main.f90
! Time                 : Mon Dec  1 09:16:28 2014
! Working directory    : /home/beck/kpp_boxmodel/0-dim_box_model_Exa2Green/kpp-2.2.1_with_Prace_Integrator
! Equation file        : kpp.kpp
! Output root filename : kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! MAIN - Main program - driver routine
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

PROGRAM kpp_Driver

  USE kpp_Model
  USE kpp_Initialize, ONLY: Initialize
  USE kpp_Parameters, ONLY: idim, jdim, kdim, idim_spot, jdim_spot, kdim_spot, NMONITOR, TAG
  USE omp_lib

  INCLUDE "mpif.h"

      REAL(kind=dp) :: T, DVAL(NSPEC)
      REAL(kind=dp) :: RSTATE(20)
      INTEGER :: ISTATE(20)
      INTEGER :: ICNTRL(20)
      REAL(kind=dp) :: RCNTRL(20)
      REAL(kind=dp) :: ref_sol(NMONITOR), rel_acc, weight
      INTEGER :: i, nbit, n_tsteps, n_tsteps_first_call, ii, jj, kk
      REAL(kind=dp) :: starttime, endtime, meantime, time_first_call
      REAL(kind=dp) :: energy_ts_init, energy_ts_final
      REAL(kind=dp) :: device_energy_ts_init, device_energy_ts_final
      REAL(kind=dp) :: mean_device_energy_ts, mean_energy_ts
      REAL(kind=dp) :: energy_init, energy_final
      REAL(kind=dp) :: device_energy_init, device_energy_final

!~~~> Initialization 

      ! get energy counter at startup
      CALL energy(energy_init)
      CALL device_energy(device_energy_init)

      DO i = 1, 20
         ISTATE(i) = 0
         ICNTRL(i) = 0
         RSTATE(i) = 0.0d0
         RCNTRL(i) = 0.0d0
      END DO


      ICNTRL(2) = 1
      ICNTRL(3) = 3


      STEPMIN = 0.0d0
      STEPMAX = 0.0d0
      
      mean_energy_ts = 0.0d0
      mean_device_energy_ts = 0.0d0
      meantime = 0.0d0
      n_tsteps = 0
      time_first_call = 0.0d0
      n_tsteps_first_call = 0
      nbit = 0

      DO i=1,NVAR
        RTOL(i) = 1.0d-2
        ATOL(i) = 1.0d-2
      END DO
      
      ! reference solution obtained from a previous reference run with
      ! KPP-2.2.1, Ros4, rtol = atol = 0.01
      ref_sol( 1 ) =    0.6472393693672319E-08    ! OP1                             
      ref_sol( 2 ) =    0.3083956643851117E-04    ! H2O2                            
      ref_sol( 3 ) =    0.5931264934946631E-03    ! HCHO                            
      ref_sol( 4 ) =    0.1386504838333425E-06    ! HO                              
      ref_sol( 5 ) =    0.7541549217546663E-02    ! NO2                             
      ref_sol( 6 ) =    0.2400627113163992E-03    ! NO                              
      ref_sol( 7 ) =    0.2038354202708597E-01    ! O3                              
      ref_sol( 8 ) =    0.2090103765938721E-06    ! NO3 

      rel_acc = 0.0D0
      weight = 0.0D0

      CALL Initialize()
      CALL InitSaveData()

      !$OMP PARALLEL DEFAULT(SHARED) &
      !$OMP PRIVATE(kk,jj,ii)
      !$OMP DO COLLAPSE(2)
      DO kk=1,kdim
         DO jj=1,jdim
            DO ii=1,idim
               ! set initial values with those of box(ii,jj,kk)
               VARTOT(1:NVAR,ii,jj,kk) = C(1:NVAR)
            ENDDO
         ENDDO
      ENDDO
      !$OMP END DO 
      !$OMP END PARALLEL

      CALL OMP_SET_DYNAMIC(.FALSE.)

!~~~> Time loop
      T = TSTART
kron: DO WHILE (T < TEND)

        ! get energy counter at startup
        CALL energy(energy_ts_init)
        CALL device_energy(device_energy_ts_init)

        CHI = CHIBE( T/60.0d+00, 48.0d+00, 2.0d+00, TAG )

        TIME = T
        CALL GetMass( C, DVAL )
        WRITE(6,991) (T-TSTART)/(TEND-TSTART)*100, T,       &
                   ( TRIM(SPC_NAMES(MONITOR(i))),           &
                     VARTOT(MONITOR(i),idim_spot,jdim_spot,kdim_spot)/CFACTOR, i=1,NMONITOR )
        CALL SaveData()
        !CALL Update_SUN() 
        CALL Update_RCONST()

        starttime = MPI_WTIME()
        CALL INTEGRATE( TIN = T, TOUT = T+DT, ISTATUS_U = ISTATE, &
             RSTATUS_U = RSTATE, &
             ICNTRL_U = ICNTRL, &
             RCNTRL_U = RCNTRL)

        endtime = MPI_WTIME()
        T = RSTATE(1)

        meantime = meantime + endtime - starttime
        n_tsteps = n_tsteps + ISTATE(3)

        IF (nbit == 0) THEN
           time_first_call = meantime
           n_tsteps_first_call = n_tsteps
        END IF
        nbit = nbit + 1

        ! get energy counter at end
        CALL energy(energy_ts_final)
        CALL device_energy(device_energy_ts_final)

        mean_energy_ts = mean_energy_ts + energy_ts_final - energy_ts_init
        mean_device_energy_ts = mean_device_energy_ts + &
             device_energy_ts_final - device_energy_ts_init

      END DO kron
!~~~> End Time loop

      CALL GetMass( C, DVAL )
      WRITE(6,991) (T-TSTART)/(TEND-TSTART)*100, T,     &
               ( TRIM(SPC_NAMES(MONITOR(i))),           &
                 VARTOT(MONITOR(i),idim_spot,jdim_spot,kdim_spot)/CFACTOR, i=1,NMONITOR )
  
      TIME = T
      CALL SaveData()
      CALL CloseSaveData()

      ! get energy counter at end
      CALL energy(energy_final)
      CALL device_energy(device_energy_final)

      i = 1
      DO WHILE (i < NMONITOR + 1)
         rel_acc = rel_acc + (ref_sol(i) - VARTOT(MONITOR(i),idim_spot,jdim_spot,kdim_spot)/CFACTOR)**2
         weight = weight + ref_sol(i)**2
         i = i + 1
      END DO
      rel_acc = SQRT(rel_acc/weight)

      WRITE(6, 989) 'Relative accuracy to ref. sol.        = ', rel_acc 
      WRITE(6, 988) 'Number of time steps    (first call)  = ', n_tsteps_first_call
      WRITE(6, 989) 'Total elapsed time      (first call)  = ', time_first_call
      WRITE(6, 988) 'Number of time steps    (in average)  = ', n_tsteps / nbit
      WRITE(6, 989) 'Total elapsed time      (in average)  = ', meantime / nbit
      WRITE(6, 989) 'Energy (J)              (in average)  = ', mean_energy_ts / nbit
      WRITE(6, 989) 'Device energy (J)       (in average)  = ', mean_device_energy_ts / nbit
      WRITE(6, 988) 'Number of time steps    (  in total)  = ', n_tsteps
      WRITE(6, 989) 'Total elapsed time      (  in total)  = ', meantime
      WRITE(6, 989) 'Energy (J)              (  in total)  = ', energy_final - energy_init
      WRITE(6, 989) 'Device energy (J)       (  in total)  = ', device_energy_final - device_energy_init
      WRITE(6, 988) 'Nb function calls                     = ', nbit 

      WRITE(6, 997) ICNTRL
      WRITE(6, 998) RCNTRL
      WRITE(6, 999) rel_acc, n_tsteps_first_call, time_first_call, n_tsteps/nbit, meantime/nbit, n_tsteps, meantime
997   FORMAT(20(I7, ","))
998   FORMAT(20(F7.2, ","))
999   FORMAT(E11.4, ",", I5, ",",E11.4, ",",I5,",", E11.4, ",",I5, ",",E11.4)

988   FORMAT(A, I11)
989   FORMAT(A, E11.4)
991   FORMAT(F6.1,'%. T=',E9.3,2X,200(A,'=',E11.4,'; '))

!==============================================================================
CONTAINS
!==============================================================================

  SUBROUTINE device_energy(e)
    IMPLICIT NONE
    REAL (kind=8), INTENT(out) :: e
    
    OPEN(unit=50, file='/sys/cray/pm_counters/accel_energy' ,action='READ')
    READ(50,*) e
    CLOSE(50)
  END SUBROUTINE device_energy

  SUBROUTINE energy(e)
    IMPLICIT NONE
    REAL (kind=8), INTENT(out) :: e
    
    OPEN(unit=50, file='/sys/cray/pm_counters/energy' ,action='READ')
    READ(50,*) e
    CLOSE(50)
  END SUBROUTINE energy

END PROGRAM kpp_Driver

! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


