!-------------------- BEGIN box_model_integrate.f90 BEGIN --------------------
! @file box_model_integrate.f90                                               
! @author charlesj                                                            
! @date 2015-01-22 16:21:36.377184                                            
! @brief Interface to time stepping integrator                                
!                                                                             
! Definitions of interface functions for the Kppa-generated                   
! time stepping integrator.  These are the Kppa "entry point" routines.       
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------




MODULE box_model_integrate

    IMPLICIT NONE


    INTERFACE
    
    INTEGER(C_INT) FUNCTION GridIntegrate(ncells, conc, tstart, tend, abstol, reltol, &
            idata, rdata, ISTATS) BIND(C, name="GridIntegrate")

        USE ISO_C_BINDING, ONLY: C_DOUBLE, C_INT, C_LONG_LONG
        USE box_model_parameters, ONLY: NVAR

        INTEGER(C_INT), VALUE, INTENT(IN) :: ncells
        REAL(C_DOUBLE), INTENT(INOUT) :: conc(NVAR*ncells)
        REAL(C_DOUBLE), VALUE, INTENT(IN) :: tstart
        REAL(C_DOUBLE), VALUE, INTENT(IN) :: tend
        REAL(C_DOUBLE), INTENT(IN) :: abstol(NVAR)
        REAL(C_DOUBLE), INTENT(IN) :: reltol(NVAR)
        INTEGER(C_INT), INTENT(INOUT) :: idata(20)
        REAL(C_DOUBLE), INTENT(INOUT) :: rdata(20)
        INTEGER(C_LONG_LONG), INTENT(OUT) :: ISTATS(8)

    END FUNCTION GridIntegrate
    END INTERFACE


END MODULE box_model_integrate

!---------------------- END box_model_integrate.f90 END ----------------------
