!---------------------- BEGIN small_parameters.f90 BEGIN ---------------------
! @file small_parameters.f90                                                  
! @author jlinford                                                            
! @date 2014-06-01 10:26:33.112717                                            
! @brief Program parameters                                                   
!                                                                             
! Integration tolerances, program constants, and species indices.             
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE small_parameters


  IMPLICIT NONE



!-----------------------------------------------------------------------------
! Integration tolerances                                                      
!-----------------------------------------------------------------------------

  ! Absolute tolerance 
  REAL(8), PARAMETER :: ATOLS = 1.0d-3
  ! Relative tolerance 
  REAL(8), PARAMETER :: RTOLS = 1.0d-4


!-----------------------------------------------------------------------------
! Concentration constants                                                     
!-----------------------------------------------------------------------------

  ! Conversion factor 
  REAL(8), PARAMETER :: CFACTOR = 1.0
  ! Default initialization value for variable species 
  REAL(8), PARAMETER :: VAR_DEFAULT = 0.0
  ! Default initialization value for fixed species 
  REAL(8), PARAMETER :: FIX_DEFAULT = 0.0


!-----------------------------------------------------------------------------
! Program constants                                                           
!-----------------------------------------------------------------------------

  ! Species count 
  INTEGER, PARAMETER :: NSPEC = 7
  ! Variable species count 
  INTEGER, PARAMETER :: NVAR = 5
  ! Fixed species count 
  INTEGER, PARAMETER :: NFIX = 2
  ! Active variable species count 
  INTEGER, PARAMETER :: NVARACT = 5
  ! Reaction (equation) count 
  INTEGER, PARAMETER :: NREACT = 10


!-----------------------------------------------------------------------------
! Numerical constants                                                         
!-----------------------------------------------------------------------------

  REAL(8), PARAMETER :: ZERO = 0.0
  REAL(8), PARAMETER :: HALF = 0.5
  REAL(8), PARAMETER :: ONE = 1.0
  REAL(8), PARAMETER :: TWO = 2.0


!-----------------------------------------------------------------------------
! Variable species indices                                                    
!-----------------------------------------------------------------------------

  INTEGER, PARAMETER :: IND_O1D = 0
  INTEGER, PARAMETER :: IND_O = 1
  INTEGER, PARAMETER :: IND_O3 = 2
  INTEGER, PARAMETER :: IND_NO = 3
  INTEGER, PARAMETER :: IND_NO2 = 4


!-----------------------------------------------------------------------------
! Fixed species indices                                                       
!-----------------------------------------------------------------------------

  INTEGER, PARAMETER :: IND_M = 5
  INTEGER, PARAMETER :: IND_O2 = 6


END MODULE small_parameters
!------------------------ END small_parameters.f90 END -----------------------
