#!/bin/bash

#-------------------------------------------------------------------------------------------------------
#
# Sylvaine Ferrachat / Grazia Frontoso 2012
#
# Set the variables for running echam 
# This file is sourced in jobsubm_echam.sh
#
# The task of creating the symlinks to input files is done elsewhere (see jobsubm_echam.sh),
# to avoid cluttering this settings file
#
# This file comprises 4 main chapters, where you should adjust your settings:
#   - General settings
#   - Compute settings
#   - ECHAM(-HAMMOZ) settings
#   - Settings for launching a slave p-proc job at the end of each echam integration
#
#-------------------------------------------------------------------------------------------------------

set -e

#------------------------------------------------------------------------------------------------------
#-- General settings:

model_dir="/users/mariaf/m7_boxmodel/grazia"    # location of the sources and bin of the model
exp="test_boxmodel"        # experiment identifier
script_dir=${model_dir}/run/${exp}                # where the jobscript and exp namelist are to be found
echam_jobscript=${script_dir}/echam_jobscript_${exp}.sh # echam batch job script name

make_source_backup=false  # set to true if you want to keep records of the current state of your code
                          # it will create a text file named "source_info_[exp]_YYYY-MM-DD_HH.mm.txt"
                          # where you'll find all details (base version number, differences to base version
                          # and how to restore your code in future)
                          # !!WARNING!! it only works if your code is a working copy from an svn repository
                          #             In the opposite case, make_source_backup will be automatically reset
                          #             to false.

#------------------------------------------------------------------------------------------------------
#-- Compute settings for machine: rosa (Cray XE6, Swiss Compting Center (CSCS), as of 2012.01)

queue_name="rosa"                       # queue name to use on current batch system
jobname="$exp"                          # batch job name
ncpus=1                                 # total number of cpus
walltime="00:01:00"                     # job estimated runtime
nproma=16                               # vector length (don't modify if you don't know about it)
account="s235"                          # project ID for accounting 
exp_dir="/scratch/rosa/$USER/${exp}/"   # where the run will be done 

#-Body-begin. Do not delete this line!
#------------------------------------------------------------------------------------------------------
#-- ECHAM6-HAMMOZ settings:

   #-- General:

model_type="echam6-hammoz"                        # model type (echam5.5-ham, echam6 or echam6-hammoz)
model_bin=${model_dir}/bin/m7_box                 # model bin name
emissions_spec=${script_dir}/emi_spec_${exp}.txt  # name of your exp emi_spec file to copy to $exp_dir

hres="T63"                    # horizontal spectral truncation
vres="L31"                    # vertical resolution
oceres="GR15"                 # resolution of the ocean model used to produce the land-sea mask
ntiles=11                     # number of tiles in the vegetation model

no_cycles=15                  # number of cycles in one integration (1 cycle = timespan between 2 'putrerun' events)
init_restart_flag=.false.     # echam restart flag at launch of this job 
                              # (in case of job chaining, the proper rerun flag will be automatically 
                              #  set when further jobs will be started)

date_start="1999,10,01,0,0,0" # start of the experiment - Should never be modified when making a rerun
date_stop="2001,01,01,0,0,0"  # end of the experiment - Can be freely adjusted during the whole experiment

input_files_version="v01_001" # version label for input files !!do not change if you don't know about it!!
scenario="RCP45"              # in case it is relevant for the given setup (using either variable GHG's
                              # ozone or climatologic aerosols, AND the experiment's time range 
                              # overlaps with [2009,2100]), choose here the scenario you'd like
                              # (RCP45, XXX, all case insensitive)
aero_dataset=aerocom_II    # aerocom or aerocom_II (case sensitive)




   #-- ECHAM6-HAMMOZ namelists:

       #-- ECHAM:

cat > ${script_dir}/namelist_${exp}.echam << EOF

!gf
iaero   = 1 
!gf

&HAMCTL
 lsoa = true
/
&HAM_M7CTL
 nwater = 1
 nonucl = 0
/
&INI_M7CTL
pap     = 1013.25 ! Pressure (Pa)
pt      = 265.0   ! Temperature (K)
prh     = 0.3     ! RH (as saturation ratio)
pipr    = 5.0     ! Ionization rate (cm-3 s-1)
pdgso4  = 5.0E4   ! H2SO4(g) production rate (cm-3 s-1)
pgso4   = 1.0E4   ! H2SO4(g) concentrations (cm-3)
paclc   = 0.0     ! cloud cover [0,1] (
                  ! set to zero unless you know what you are doing)
pforest = 1.0
paerml  = 1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
                  ! Aerosol mass concentrations for individual compounds, 
                  !(molec. cm-3 for sulfate and
                  ! ug m-3 for bc, oc, ss, and dust)
                  ! Order: SO4_NS, SO4_KS, SO4_AS, SO4_CS
                  !        BC_KS, BC_KI, BC_AS, BC_CS,
                  !        OC_KS, OC_KI, OC_AS, OC_CS,
                  !        SS_AS, SS_CS,
                  !        DU_AS, DU_AI, DU_CS, DU_CI
paernl  = 1.0,1.0,1.0,1.0,1.0,1.0,1.0
                  ! Particle number concentrations for each mode (cm-3)
                  ! Order: NS, KS, AS, CS, KI, AI, CI
pm6rp   = 1.0,1.0,1.0,1.0,1.0,1.0,1.0
                  ! Order: NS, KS, AS, CS, KI, AI, CI
                  ! Particle mean mode actual radius for each mode 
                  ! (wet for soluble and dry for insoluble modes) (cm) 
pm6dry  = 1.0,1.0,1.0,1.0
                  ! Particle dry radius for each soluble modes (cm)
                  ! Order: NS, KS, AS, CS
prhop   = 1.0,1.0,1.0,1.0,1.0,1.0,1.0
                  ! Mean mode particle density for each mode (g cm-3)
                  ! Order: NS, KS, AS, CS, KI, AI, CI
pww     = 0.0,0.0,0.0,0.0
                  ! Water content for each mode [kg(water) m-3(air)]
                  ! Order: NS, KS, AS, CS, KI, AI, CI
/
EOF


       #-- JS-BACH:

cat > ${script_dir}/namelist_${exp}.jsbach <<EOF
&JSBACH_CTL
  standalone = .false.
  ! --- number of tiles ---
  ntiles = ${ntiles}

  ! --- options to activate the different jsbach modules ---
  use_bethy = .true.
  use_phenology = .true.
  use_albedo = .true.
  use_dynveg = .false.

  ! --- output options ---
  file_type = "NETCDF"
  lpost_echam = .false.
  debug = .false.
/
&ALBEDO_CTL
  use_albedocanopy = .false.
/
&CBALANCE_CTL
  read_cpools = .false.
/
&DYNVEG_CTL
  read_fpc = .false.
  dynveg_feedback = .false.
/
&CLIMBUF_CTL
  init_running_means = .false.
/
EOF

#-Body-end. Do not delete this line!

#------------------------------------------------------------------------------------------------------
#-- Settings for launching a slave p-proc job at the end of each echam integration
#   This may be specific for machine: rosa (Cray XE6, Swiss Compting Center (CSCS), as of 2012.01)

flag_p_proc=true                                          # flag to launch the p-proc
p_proc_script=/project/s235/Scripts/Pproc/copy_remote.sh  # p-proc script (no batch directives in there)
p_proc_dir=/project/${account}/$USER/${exp}               # remote directory where p_proc is done
p_proc_jobname="copy_remote"                              # batch jobname for executing the p_proc_script
p_proc_walltime="03:00:00"                                # requested walltime for the p_proc batch job
