#!/bin/bash

#-------------------------------------------------------------------------------------------------------
# Sylvaine Ferrachat 2012
# 
# The following is the middle part (body) of a settings file that will be sourced 
# by jobsubm_echam.sh to setup and launch an echam job.
#
# The task of assembling together all the pieces of the settings file is done by prepare_run.sh.
#
# These pieces are:
#
#     - Header: general settings and compute settings:
#               - there are mostly machine-dependent, and not echam version-dependent
#               --> to be found in each machine_config/machine_name/
#
#     - Body [current file]: echam(-hammoz) settings: 
#               - these are machine-independent, and echam version-dependent
#               --> to be found in the model distribution (distribution default templates), in
#                   any user's already existing settings, or in run_configs/ as a rescue for model versions
#                   older than the first inclusion of this into echam distributions
#
#     - Tail: settings for launching any arbitrary slave p-proc job at the end of each echam integration:
#               - these are machine-dependent, and echam version-independent
#               --> to be found in each machine_config/machine_name/
#
#-------------------------------------------------------------------------------------------------------

#-Body-begin. Do not delete this line!
#------------------------------------------------------------------------------------------------------
#-- ECHAM6-HAMMOZ settings:

   #-- General:

model_type="echam6-hammoz"                        # model type (echam5.5-ham, echam6 or echam6-hammoz)
model_bin=${model_dir}/bin/echam6                 # model bin name
emissions_spec=${script_dir}/emi_spec_${exp}.txt  # name of your exp emi_spec file to copy to $exp_dir

hres="T63"                    # horizontal spectral truncation
vres="L31"                    # vertical resolution
oceres="GR15"                 # resolution of the ocean model used to produce the land-sea mask
ntiles=11                     # number of tiles in the vegetation model

no_cycles=15                  # number of cycles in one integration (1 cycle = timespan between 2 'putrerun' events)
init_restart_flag=.false.     # echam restart flag at launch of this job 
                              # (in case of job chaining, the proper rerun flag will be automatically 
                              #  set when further jobs will be started)

date_start="1999,10,01,0,0,0" # start of the experiment - Should never be modified when making a rerun
date_stop="2001,01,01,0,0,0"  # end of the experiment - Can be freely adjusted during the whole experiment

input_files_version="v01_001" # version label for input files !!do not change if you don't know about it!!
scenario="RCP45"              # in case it is relevant for the given setup (using either variable GHG's
                              # ozone or climatologic aerosols, AND the experiment's time range 
                              # overlaps with [2009,2100]), choose here the scenario you'd like
                              # (RCP45, XXX, all case insensitive)
aero_dataset=aerocom_II       # aerocom_II or aerocom (case sensitive)

   #-- ECHAM6-HAMMOZ namelists:

       #-- ECHAM:

cat > ${script_dir}/namelist_${exp}.echam << EOF
&PARCTL
 nproca = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
 nprocb = WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID VALUE HERE
/
&RUNCTL 
 nproma         = ${nproma}
 lresume        = $init_restart_flag,
 lmidatm        = .false.
 out_datapath   = "$exp_dir"
 out_expname    = "$exp"
 out_filetype   = 2     ! 1--> grib; 2--> NetCDF; 6--> NetCDF4;
 trac_filetype  = 2     ! 1--> grib; 2--> NetCDF;
 rerun_filetype = 2     ! 2--> NetCDF; 4--> NetCDF2
 dt_start       = $date_start
 dt_stop        = $date_stop
 putdata        = 1,'months','last',0
 trigfiles      = 1, 'months', 'first', 0
 putrerun       = 1,'months','last',0
 no_cycles      = ${no_cycles}, 
 lamip          = .false.
 lnudge         = .false.
 lipcc          = .false.
 ldebugs        = .false.
 ltimer         = .false.
/
&SUBMODELCTL
 lmethox       = .true.
 lham          = .true.
 lmegan        = .false. 
 lmoz          = .false.
 lhammoz       = .false.
 emi_basepath  = "[WILL BE AUTOMATICALLY SET HERE UNLESS YOU DEFINE A VALID PATH HERE]"
/
&SUBMDIAGCTL
 vphysc_lpost     = .true.
 vphyscnam        = 'all'
 wetdep_lpost     = .true. 
 wetdepnam        = 'all' 
 wetdep_gastrac   = 'SO2', 'SO4_gas'
 wetdep_keytype   = 1 
 drydep_lpost     = .true. 
 drydepnam        = 'all' 
 drydep_gastrac   = 'SO2', 'SO4_gas'
 drydep_keytype   = 1 
 sedi_lpost       = .true. 
 sedinam          = 'all' 
 sedi_keytype     = 1 
 emi_lpost        = .true.
 emi_lpost_sector = .true.
 eminam           = 'all'
 emi_gastrac      = 'all'
/
&DEBUGSCTL
 putdebug_stream = 1, 'days', 'last', 0
/
&RADCTL
 iaero   = 1     ! 1 for interactive (lham=true), 2 for Tanre 3 for Kinne  
 l_srtm  = .true.
 l_lrtm  = .true.
 isolrad = 3      
 io3     = 4     ! 3 --> obsolete! climatology from IPCC-NetCDF file, 4--> CMIP5 new data
/
&PHYSCTL
 lcover         = .false.
 lcdnc_progn    = .true.
 ncd_activ      = 1
 nic_cirrus     = 2
 nauto          = 2
/
&HAM_DUSTCTL
 ndustE2 = 4
/
&HAMCTL
 nseasalt      = 5
 nwetdep       = 2
 naerorad      = 1
 nrad          = 0, 3, 3, 3, 3, 3, 3
 nradmix       = 0, 1, 1, 1, 1, 1, 1  
 nraddiag      = 1
/
&NDGCTL
 inudgformat     = 2
 dt_nudg_start   = $date_start
 dt_nudg_stop    = $date_stop
 lnudgdbx        = .false.
 lnudgini        = .true.
 nudglmin        = 1
 nudglmax        = ${vres#L}
 nudgsmin        = 0
 nudgsmax        = ${hres#T}
 lnudgimp        = .TRUE.
 nudgd           = ${vres#L}*0.579
 nudgt           = ${vres#L}*1.16
 nudgv           = ${vres#L}*4.63
 nudgp           = 1.16
 ltintlin        = .false.
 ldamplin        = .true.
 nudgdamp        = 1.
 nudgdsize       = 0.5
 ndg_file_nc    = "ndg%y4%m2.nc"
/
EOF

       #-- JS-BACH:

cat > ${script_dir}/namelist_${exp}.jsbach <<EOF
&JSBACH_CTL
  standalone = .false.
  ! --- number of tiles ---
  ntiles = ${ntiles}

  ! --- options to activate the different jsbach modules ---
  use_bethy = .true.
  use_phenology = .true.
  use_albedo = .true.
  use_dynveg = .false.

  ! --- output options ---
  file_type = "NETCDF"
  lpost_echam = .false.
  debug = .false.
/
&ALBEDO_CTL
  use_albedocanopy = .false.
/
&CBALANCE_CTL
  read_cpools = .false.
/
&DYNVEG_CTL
  read_fpc = .false.
  dynveg_feedback = .false.
/
&CLIMBUF_CTL
  init_running_means = .false.
/
EOF

       #-- Mean-values streams:

#SF uncomment the following if you need to compute online monthly means:

#cat >> ${script_dir}/namelist_${exp}.echam << EOF
#&MVSTREAMCTL
#  m_stream_name = 'ham', 'rad', 'tracer', 'vphysc', 'activ' 
#/
#EOF

cat > ${script_dir}/ham.nml <<EOF
&MVCTL
  PUTMEAN = 1,'months','last',0
  meannam = 'all'
/
EOF

cat > ${script_dir}/rad.nml <<EOF
&MVCTL
  PUTMEAN = 1,'months','last',0
  meannam = 'all'
/
EOF

cat > ${script_dir}/tracer.nml <<EOF
&MVCTL
  PUTMEAN = 1,'months','last',0
  meannam = 'all' 
/
EOF

cat > ${script_dir}/vphysc.nml <<EOF
&MVCTL
  PUTMEAN = 1,'months','last',0
  meannam = 'all'
/
EOF

cat > ${script_dir}/activ.nml <<EOF
&MVCTL
  PUTMEAN = 1,'months','last',0
  meannam = 'all'
/
EOF

#-Body-end. Do not delete this line!
