/*----------------------- BEGIN kppa_CUDA_rates.h BEGIN -----------------------*/
/* @file kppa_CUDA_rates.h                                                     */
/* @author charlesj                                                            */
/* @date 2015-01-22 16:21:36.008050                                            */
/* @brief Reaction rate calculation and utility functions                      */
/*                                                                             */
/* Reaction rate calculation and utility functions                             */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __KPPA_CUDA_RATES_H__
#define __KPPA_CUDA_RATES_H__



#ifdef __cplusplus
extern "C" {
#endif


/*----------------------------------- Rates -----------------------------------*/
/* Calculates reaction rate coefficients                                       */
/*                                                                             */
/* @param[in]     ncells32 A multiple of 32 grid cells                         */
/* @param[in]     time     Integration time                                    */
/* @param[in]     idx      Current grid cell index                             */
/* @param[out]    d_rct    Reaction rates in device memory                     */
/*-----------------------------------------------------------------------------*/
void Rates(size_t const ncells32, double const time, size_t const idx,
    double* d_rct);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __KPPA_CUDA_RATES_H__ */
/*------------------------- END kppa_CUDA_rates.h END -------------------------*/
