/*------------------- BEGIN kppa_CUDA_cu_parameters.h BEGIN -------------------*/
/* @file kppa_CUDA_cu_parameters.h                                             */
/* @author charlesj                                                            */
/* @date 2015-01-22 16:21:35.607681                                            */
/* @brief CUDA interface to program parameters                                 */
/*                                                                             */
/* CUDA interface to program parameters, such as integration tolerances,       */
/* program constants, and species indices.                                     */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __KPPA_CUDA_CU_PARAMETERS_H__
#define __KPPA_CUDA_CU_PARAMETERS_H__



#ifdef __cplusplus
extern "C" {
#endif



/*-----------------------------------------------------------------------------*/
/* Integration tolerances                                                      */
/*-----------------------------------------------------------------------------*/

/* Absolute tolerance */
#define ATOLS            ((double)(1.0))
/* Relative tolerance */
#define RTOLS            ((double)(0.001))


/*-----------------------------------------------------------------------------*/
/* Concentration constants                                                     */
/*-----------------------------------------------------------------------------*/

/* Conversion factor */
#define CFACTOR          ((double)(25500000000.0))
/* Default initialization value for variable species */
#define VAR_DEFAULT      ((double)(1e-20))
/* Default initialization value for fixed species */
#define FIX_DEFAULT      ((double)(1e-20))


/*-----------------------------------------------------------------------------*/
/* Program constants                                                           */
/*-----------------------------------------------------------------------------*/

/* Species count */
#define NSPEC            ((size_t)(83))
/* Variable species count */
#define NVAR             ((size_t)(82))
/* Fixed species count */
#define NFIX             ((size_t)(1))
/* Active variable species count */
#define NVARACT          ((size_t)(76))
/* Reaction (equation) count */
#define NREACT           ((size_t)(194))


/*-----------------------------------------------------------------------------*/
/* Numerical constants                                                         */
/*-----------------------------------------------------------------------------*/

#define ZERO             ((double)(0.0))
#define HALF             ((double)(0.5))
#define ONE              ((double)(1.0))
#define TWO              ((double)(2.0))


/*-----------------------------------------------------------------------------*/
/* Variable species indices                                                    */
/*-----------------------------------------------------------------------------*/

#define IND_NH3          ((size_t)(0))
#define IND_N2           ((size_t)(1))
#define IND_SULF         ((size_t)(2))
#define IND_ORA1         ((size_t)(3))
#define IND_ORA2         ((size_t)(4))
#define IND_CS1          ((size_t)(5))
#define IND_CO2          ((size_t)(6))
#define IND_H2           ((size_t)(7))
#define IND_ETH          ((size_t)(8))
#define IND_ISHP         ((size_t)(9))
#define IND_HC5          ((size_t)(10))
#define IND_TPAN         ((size_t)(11))
#define IND_HONO         ((size_t)(12))
#define IND_DMSO         ((size_t)(13))
#define IND_HC8          ((size_t)(14))
#define IND_SO2          ((size_t)(15))
#define IND_N2O5         ((size_t)(16))
#define IND_MAHP         ((size_t)(17))
#define IND_DMS          ((size_t)(18))
#define IND_TOL          ((size_t)(19))
#define IND_XYL          ((size_t)(20))
#define IND_HC3          ((size_t)(21))
#define IND_NALD         ((size_t)(22))
#define IND_CS10         ((size_t)(23))
#define IND_CS100        ((size_t)(24))
#define IND_CS1000       ((size_t)(25))
#define IND_O1D          ((size_t)(26))
#define IND_PAA          ((size_t)(27))
#define IND_MPAN         ((size_t)(28))
#define IND_OP1          ((size_t)(29))
#define IND_CSL          ((size_t)(30))
#define IND_HACE         ((size_t)(31))
#define IND_HNO4         ((size_t)(32))
#define IND_PAN          ((size_t)(33))
#define IND_O3P          ((size_t)(34))
#define IND_H2O2         ((size_t)(35))
#define IND_OL2          ((size_t)(36))
#define IND_ISOP         ((size_t)(37))
#define IND_ISON         ((size_t)(38))
#define IND_O2           ((size_t)(39))
#define IND_API          ((size_t)(40))
#define IND_CO           ((size_t)(41))
#define IND_LIM          ((size_t)(42))
#define IND_OLT          ((size_t)(43))
#define IND_HNO3         ((size_t)(44))
#define IND_ISO          ((size_t)(45))
#define IND_GLY          ((size_t)(46))
#define IND_XNO2         ((size_t)(47))
#define IND_XYLP         ((size_t)(48))
#define IND_MACR         ((size_t)(49))
#define IND_DCB          ((size_t)(50))
#define IND_HC5P         ((size_t)(51))
#define IND_HC8P         ((size_t)(52))
#define IND_OLIP         ((size_t)(53))
#define IND_KET          ((size_t)(54))
#define IND_OL2P         ((size_t)(55))
#define IND_OLTP         ((size_t)(56))
#define IND_XO2          ((size_t)(57))
#define IND_TOLP         ((size_t)(58))
#define IND_OP2          ((size_t)(59))
#define IND_MACP         ((size_t)(60))
#define IND_OLN          ((size_t)(61))
#define IND_MGLY         ((size_t)(62))
#define IND_HCHO         ((size_t)(63))
#define IND_TCO3         ((size_t)(64))
#define IND_H2O          ((size_t)(65))
#define IND_LIMP         ((size_t)(66))
#define IND_APIP         ((size_t)(67))
#define IND_OLI          ((size_t)(68))
#define IND_ONIT         ((size_t)(69))
#define IND_ALD          ((size_t)(70))
#define IND_ETHP         ((size_t)(71))
#define IND_HO2          ((size_t)(72))
#define IND_HC3P         ((size_t)(73))
#define IND_NO2          ((size_t)(74))
#define IND_MO2          ((size_t)(75))
#define IND_NO           ((size_t)(76))
#define IND_O3           ((size_t)(77))
#define IND_KETP         ((size_t)(78))
#define IND_NO3          ((size_t)(79))
#define IND_ACO3         ((size_t)(80))
#define IND_HO           ((size_t)(81))


/*-----------------------------------------------------------------------------*/
/* Fixed species indices                                                       */
/*-----------------------------------------------------------------------------*/

#define IND_CH4          ((size_t)(82))



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __KPPA_CUDA_CU_PARAMETERS_H__ */
/*--------------------- END kppa_CUDA_cu_parameters.h END ---------------------*/
