! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_Rates.f90
! Time                 : Thu Jul 30 10:13:42 2015
! Working directory    : /users/charlesj/KPP_BOXMODEL/extended_box_model/kpp-2.2.3
! Equation file        : kpp.kpp
! Output root filename : kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kpp_Rates

  !  USE fastexp
  USE kpp_Parameters
  USE kpp_Global

  IMPLICIT NONE

!!$  INCLUDE "fastexp.include"

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions



FUNCTION CHIBE(ZEIT,GB,GL,TAG)
      REAL(dp) :: CHIBE,ZEIT,GB,GL,TAG,SD,CD,FP,OM,SH,SH1,CHI,DEKL
!C     BERECHNUNG DES SONNENWINKELS CHI
!C
      DEKL = 23.45E0*SIN((280.1E0+0.981E0*TAG)*0.01745329E0)
      FP = 0.01745329E0
      SD = SIN(DEKL*FP)
      CD = COS(DEKL*FP)
!CU    OM = (12.E0-(ZEIT+GL/15.E0))*0.261799388E0
!CU **** TEILER /60. EINGEFUEGT DA ZEIT IN MINUTEN UEBERGEBEN WIRD ****
      OM = (12.E0-(ZEIT/60.+GL/15.E0))*0.261799388E0
      SH = SIN(GB*FP)*SD+COS(GB*FP)*CD*COS(OM)
      SH1 = ASIN(SH)*180./3.141592
!CU    IF(SH1.LT.0.) SH1=0.
      CHI=90.-SH1
!cn *** fester sonnenzenitwinkel vorgeben
!cN      chi=25.
!cn *** !!!
      CHI=3.141592/180.*CHI
      CHIBE=CHI
END FUNCTION CHIBE

FUNCTION PHUX(X,Y,Z,CHI)                            
!C                                                                          
!C     CALCULATION OF PHOTOLYSIS FREQUENCY WITH ALGORITHM FROM              
!C     ROETHS FLUX-PROGAM                                                  
!C     CHI IN RADIAN                                                        
!C     X,Y,Z FROM ROETH                                                     
!C     X  IS PHOTOLYSIS FREQUENCY IN 1/S FOR SOLAR ZENITH ANGLE CHI=0 DEG   
!C                                                                          
!C     KUHN 07.09.93                                                
!C                                                                          
      IMPLICIT NONE                                                        
      REAL(dp) :: X,Y,Z,CHI,CHIZ,YCHIZ,EYCHIZ, PHUX                
      REAL(dp), PARAMETER :: MINYZ = -30, &
                             EMINYZ = 9.357623D-14  !EMINYZ=EXP(MINYZ)   
      CHIZ   = CHI * Z                                                     
      IF (CHIZ.LT.1.57079632679489D0) THEN                                 
         YCHIZ = Y * (1.0 - (1.0/ COS(CHIZ) ) )                            
         IF (YCHIZ.GT.MINYZ) THEN                                          
            EYCHIZ =  DEXP (YCHIZ)                                         
         ELSE                                                              
            EYCHIZ =  EMINYZ                                               
         ENDIF                                                             
      ELSE                                                                 
         EYCHIZ = EMINYZ                                                   
      ENDIF                                                                
      PHUX = X * EYCHIZ                                                    
!      PHUX =0.			!ik: ohne photolyse
END FUNCTION PHUX

!C
!C*********************************************************************
!C Die Funktion TROE bestimmt die Werte der Troefunktion
!C nach Stockwell et al. [2],
!C die die Druckabhaengigkeit von Reaktionskonstanten durch eine
!C quasi-bimolekulare Reaktionskonstante beschreibt.
!C*********************************************************************
!C
 FUNCTION TROE( K0300, Q, KU300, R, M, T )
!C CALCULATION OF RATE CONSTANTS FOR TROE REACTIONS
!      IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: K0300, Q, KU300, R, M, T, TROE
      REAL(dp) :: tt, k0, ku, k0m, kk, lgkk, e, f
      TT = T / 3.D2
      K0 = K0300 / TT**Q
      KU = KU300 / TT**R
      K0M = K0 * M
      KK = K0M / KU
      LGKK = 0.434294481D0 * LOG(KK)
      E = 1.D0 / ( 1.D0 + LGKK*LGKK )
      F = 0.6D0 ** E
      TROE = F * K0M / ( 1.D0 + KK )
END FUNCTION TROE

!C
!C**********************************************************************
!C Die Funktion EQT [2] bestimmt die Reaktionskonstanten fuer
!C HNO4 --> H2O + NO2 und N2O5 --> NO2 + NO3
!C**********************************************************************
!C
FUNCTION EQT( K0300, Q, KU300, R, M, T, A, B )
      !IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: K0300, Q, KU300, R, M, T, A, B, EQT
      REAL(dp) :: kh
      KH = TROE( K0300, Q, KU300, R, M, T )
      EQT = KH * A *DEXP( -B / T )
END FUNCTION EQT

FUNCTION EQT2(M, T)
      !IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: K0300, Q, KU300, R, M, T, A, B, EQT2
      REAL(dp) :: kh
      K0300 = 1.8d-31
      Q = 3.2d0
      KU300 = 4.7d-12
      R = 1.4d0
      A = 4.76d+26
      B = 10900.d0
      KH = TROE( K0300, Q, KU300, R, M, T )
      EQT2 = KH * A *DEXP( -B / T )
END FUNCTION EQT2

!C
!C**********************************************************************
!C Die Funktion SPEZ bestimmt die Reaktionskonstante fuer
!C HNO3 + HO --> H2O + NO3
!C**********************************************************************
!C
FUNCTION SPEZ(A0,B0,A2,B2,A3,B3,M,T)
!C SPECIAL RATE CONSTANTS
      !IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: A0,B0,A2,B2,A3,B3,M,T, SPEZ
      REAL(dp) :: k0, k2, k3
      K0 = A0*DEXP(B0/T)
      K2 = A2*DEXP(B2/T)
      K3 = A3*M*DEXP(B3/T)
      SPEZ = K0 + K3 / ( 1 + K3/K2 )
END FUNCTION SPEZ


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE kpp_Parameters
      !USE kpp_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )

  REAL(kind=dp) :: TEMP_INV
  REAL(kind=dp) :: C_1
  REAL(kind=dp) :: C_2
  REAL(kind=dp) :: C_3

  TEMP_INV = 1D+00 / TEMP
  C_1 = EXP(220.*TEMP_INV)
  C_2 = EXP(1300.*TEMP_INV)
  C_3 = EXP(180.*TEMP_INV)

! Begin INLINED RCONST

! End INLINED RCONST

  RCONST(1) = (PHUX(1.07D-02,1.01319D+00,0.83330D+00,Chi))
  RCONST(2) = (PHUX(3.22D-05,4.45037D+00,0.78028D+00,Chi))
  RCONST(3) = (PHUX(5.36D-04,0.34764D+00,0.91030D+00,Chi))
  RCONST(4) = (PHUX(8.96D-04,0.99438D+00,0.83295D+00,Chi))
  RCONST(5) = (PHUX(5.48D-07,2.86922D+00,0.79561D+00,Chi))
  RCONST(6) = (PHUX(3.90D-06,2.37354D+00,0.79830D+00,Chi)+EQT2(M,TEMP))
  RCONST(7) = (PHUX(2.74D-02,0.26226D+00,0.92849D+00,Chi))
  RCONST(8) = (PHUX(2.73D-01,0.29327D+00,0.92401D+00,Chi))
  RCONST(9) = (PHUX(7.78D-06,1.91463D+00,0.79810D+00,Chi))
  RCONST(10) = (PHUX(4.92D-05,1.60973D+00,0.80184D+00,Chi))
  RCONST(11) = (PHUX(4.05D-05,2.06917D+00,0.80267D+00,Chi))
  RCONST(12) = (PHUX(5.40D-06,2.52915D+00,0.79722D+00,Chi))
  RCONST(13) = (PHUX(6.37D-06,1.76570D+00,0.80004D+00,Chi))
  RCONST(14) = (PHUX(6.37D-06,1.76570D+00,0.80004D+00,Chi))
  RCONST(15) = (PHUX(6.10D-09,9.17009D+00,0.72585D+00,Chi))
  RCONST(16) = (PHUX(1.32D-05,2.46350D+00,0.79768D+00,Chi))
  RCONST(17) = (PHUX(3.11D-03,0.55016D+00,0.88313D+00,Chi))
  RCONST(18) = (PHUX(3.11D-03,0.55016D+00,0.88313D+00,Chi))
  RCONST(19) = (PHUX(1.85D-03,0.57967D+00,0.87921D+00,Chi))
  RCONST(20) = (PHUX(6.39D-04,1.53712D+00,0.80233D+00,Chi))
  RCONST(21) = (PHUX(7.20D-08,9.11436D+00,0.72600D+00,Chi))
  RCONST(22) = (M*6.0E-34*(TEMP/300.)**(-2.3))
  RCONST(23) = (6.50E-12*EXP(120.*TEMP_INV))
  RCONST(24) = (2.00E-11*EXP(130.*TEMP_INV))
  RCONST(25) = (3.20E-11*EXP(67.*TEMP_INV))
! RCONST(26) = constant rate coefficient
  RCONST(27) = (1.4E-12*EXP(-1310.*TEMP_INV))
  RCONST(28) = (1.70E-12*EXP(-940.*TEMP_INV))
  RCONST(29) = (1.10E-14*EXP(-500.*TEMP_INV))
  RCONST(30) = (3.45E-12*EXP(270.*TEMP_INV))
  RCONST(31) = (TROE(1.8D-31,3.2d0,4.7D-12,1.4d0,M,TEMP))
  RCONST(32) = (2.2E-13*EXP(620.*TEMP_INV)+1.9E-33*M*EXP(980.*TEMP_INV))
  RCONST(33) = (3.08d-34*EXP(2820.*TEMP_INV)+2.66d-54*M*EXP(3180.*TEMP_INV))
  RCONST(34) = (3.30E-12*EXP(-200.*TEMP_INV))
  RCONST(35) = (TROE(7.0d-31,2.6d0,1.5d-11,0.5d0,M,TEMP))
  RCONST(36) = (3.30E-39*EXP(530.*TEMP_INV))
  RCONST(37) = (1.40E-13*EXP(-2470.*TEMP_INV))
  RCONST(38) = (1.80E-11*EXP(110.*TEMP_INV))
  RCONST(39) = (2.50E-14*EXP(-1230.*TEMP_INV))
! RCONST(40) = constant rate coefficient
  RCONST(41) = (TROE(2.2d-30,4.3d0,1.5d-12,0.5d0,M,TEMP))
  RCONST(42) = (EQT(2.2d-30,4.3d0,1.5d-12,0.5d0,M,TEMP,9.09d+26,11200.d0))
! RCONST(43) = constant rate coefficient
  RCONST(44) = (TROE(2.6d-30,3.2d0,2.4d-11,1.3d0,M,TEMP))
  RCONST(45) = (SPEZ(7.2d-15,785.d0,4.1d-16,1440.d0,1.9d-33,725.d0,M,TEMP))
  RCONST(46) = (1.30E-12*EXP(380.*TEMP_INV))
  RCONST(47) = (4.80E-11*EXP(250.*TEMP_INV))
  RCONST(48) = (TROE(3.0d-31,3.3d0,1.5d-12,0.0d0,M,TEMP))
  RCONST(49) = (1.5E-13*(1.0+2.439E-20*M))
  RCONST(50) = (TEMP*TEMP*6.95E-18*EXP(-1280.*TEMP_INV))
  RCONST(51) = (TEMP*TEMP*1.37E-17*EXP(-444.*TEMP_INV))
  RCONST(52) = (1.59E-11*EXP(-540.*TEMP_INV))
  RCONST(53) = (1.73E-11*EXP(-380.*TEMP_INV))
  RCONST(54) = (3.64E-11*EXP(-380.*TEMP_INV))
  RCONST(55) = (2.15E-12*EXP(411.*TEMP_INV))
  RCONST(56) = (5.32E-12*EXP(504.*TEMP_INV))
  RCONST(57) = (1.07E-11*EXP(549.*TEMP_INV))
  RCONST(58) = (2.10E-12*EXP(322.*TEMP_INV))
  RCONST(59) = (1.89E-11*EXP(116.*TEMP_INV))
! RCONST(60) = constant rate coefficient
! RCONST(61) = constant rate coefficient
  RCONST(62) = (6.87E-12*EXP(256.*TEMP_INV))
  RCONST(63) = (1.20E-11*EXP(-745.*TEMP_INV))
! RCONST(64) = constant rate coefficient
! RCONST(65) = constant rate coefficient
! RCONST(66) = constant rate coefficient
! RCONST(67) = constant rate coefficient
! RCONST(68) = constant rate coefficient
! RCONST(69) = constant rate coefficient
  RCONST(70) = (TEMP*TEMP*6.85E-18*EXP(-444.*TEMP_INV))
  RCONST(71) = (1.55E-11*EXP(-540.*TEMP_INV))
  RCONST(72) = (2.55E-11*EXP(409.*TEMP_INV))
  RCONST(73) = (2.6E-12*EXP(380.*TEMP_INV))
  RCONST(74) = (2.E16*EXP(-13500.*TEMP_INV))
! RCONST(75) = constant rate coefficient
  RCONST(76) = (1.95E16*EXP(-13543.*TEMP_INV))
  RCONST(77) = (4.20E-12*C_3)
  RCONST(78) = (4.20E-12*C_3)
  RCONST(79) = (4.20E-12*C_3)
  RCONST(80) = (4.20E-12*C_3)
  RCONST(81) = (4.20E-12*C_3)
  RCONST(82) = (4.20E-12*C_3)
  RCONST(83) = (4.20E-12*C_3)
  RCONST(84) = (3.50E-11*EXP(-180.*TEMP_INV))
  RCONST(85) = (4.20E-12*C_3)
  RCONST(86) = (4.20E-12*C_3)
  RCONST(87) = (4.20E-12*C_3)
  RCONST(88) = (4.20E-12*C_3)
  RCONST(89) = (4.20E-12*C_3)
  RCONST(90) = (4.20E-12*C_3)
  RCONST(91) = (6.00E-13*EXP(-2058.*TEMP_INV))
  RCONST(92) = (1.40E-12*EXP(-1900.*TEMP_INV))
  RCONST(93) = (6.00E-13*EXP(-2058.*TEMP_INV))
  RCONST(94) = (1.40E-12*EXP(-1900.*TEMP_INV))
  RCONST(95) = (1.40E-12*EXP(-1900.*TEMP_INV))
! RCONST(96) = constant rate coefficient
  RCONST(97) = (2.00E-12*EXP(-2923.*TEMP_INV))
  RCONST(98) = (1.00E-11*EXP(-1895.*TEMP_INV))
  RCONST(99) = (3.23E-11*EXP(-975.*TEMP_INV))
! RCONST(100) = constant rate coefficient
  RCONST(101) = (1.20E-14*EXP(-2633.*TEMP_INV))
  RCONST(102) = (1.32E-14*EXP(-2105.*TEMP_INV))
  RCONST(103) = (7.29E-15*EXP(-1136.*TEMP_INV))
  RCONST(104) = (1.23E-14*EXP(-2013.*TEMP_INV))
  RCONST(105) = (7.70E-14*C_2)
  RCONST(106) = (7.70E-14*C_2)
  RCONST(107) = (7.70E-14*C_2)
  RCONST(108) = (7.70E-14*C_2)
  RCONST(109) = (7.70E-14*C_2)
  RCONST(110) = (7.70E-14*C_2)
  RCONST(111) = (7.70E-14*C_2)
  RCONST(112) = (7.70E-14*C_2)
  RCONST(113) = (7.70E-14*C_2)
  RCONST(114) = (7.70E-14*C_2)
  RCONST(115) = (7.70E-14*C_2)
  RCONST(116) = (7.70E-14*C_2)
  RCONST(117) = (7.70E-14*C_2)
  RCONST(118) = (7.70E-14*C_2)
  RCONST(119) = (1.90E-13*C_1)
  RCONST(120) = (1.40E-13*C_1)
  RCONST(121) = (4.20E-14*C_1)
  RCONST(122) = (3.40E-14*C_1)
  RCONST(123) = (2.90E-14*C_1)
  RCONST(124) = (1.40E-13*C_1)
  RCONST(125) = (1.40E-13*C_1)
  RCONST(126) = (1.70E-14*C_1)
  RCONST(127) = (1.70E-14*C_1)
  RCONST(128) = (9.60E-13*C_1)
  RCONST(129) = (1.70E-14*C_1)
  RCONST(130) = (1.70E-14*C_1)
  RCONST(131) = (9.60E-13*C_1)
  RCONST(132) = (3.40E-13*C_1)
  RCONST(133) = (1.00E-13*C_1)
  RCONST(134) = (8.40E-14*C_1)
  RCONST(135) = (7.20E-14*C_1)
  RCONST(136) = (3.40E-13*C_1)
  RCONST(137) = (3.40E-13*C_1)
  RCONST(138) = (4.20E-14*C_1)
  RCONST(139) = (4.20E-14*C_1)
  RCONST(140) = (1.19E-12*C_1)
  RCONST(141) = (4.20E-14*C_1)
  RCONST(142) = (4.20E-14*C_1)
  RCONST(143) = (1.19E-12*C_1)
  RCONST(144) = (7.70E-14*C_2)
  RCONST(145) = (1.70E-14*C_1)
  RCONST(146) = (4.20E-14*C_1)
  RCONST(147) = (4.20E-12*C_3)
  RCONST(148) = (4.20E-12*C_3)
  RCONST(149) = (7.70E-14*C_2)
  RCONST(150) = (1.70E-14*C_1)
  RCONST(151) = (4.20E-14*C_1)
  RCONST(152) = (1.70E-14*C_1)
  RCONST(153) = (4.20E-14*C_1)
  RCONST(154) = (3.60E-16*C_1)
  RCONST(155) = (1.21E-11*EXP(444.*TEMP_INV))
  RCONST(156) = (ARR2(1.19E-12,490.))
  RCONST(157) = (ARR2(1.01E-15,-736.))
! RCONST(158) = constant rate coefficient
! RCONST(159) = constant rate coefficient
  RCONST(160) = (ARR2(3.56E-14,708.))
  RCONST(161) = (ARR2(7.40E-13,765.))
! RCONST(162) = constant rate coefficient
! RCONST(163) = constant rate coefficient
! RCONST(164) = constant rate coefficient
! RCONST(165) = constant rate coefficient
! RCONST(166) = constant rate coefficient
! RCONST(167) = constant rate coefficient
  RCONST(168) = (ARR2(3.56E-14,708.))
  RCONST(169) = (ARR2(7.40E-13,765.))
! RCONST(170) = constant rate coefficient
  RCONST(171) = (ARR2(2.43E-12,360.))
  RCONST(172) = (ARR2(2.05E-13,1300.))
! RCONST(173) = constant rate coefficient
! RCONST(174) = constant rate coefficient
! RCONST(175) = constant rate coefficient
  RCONST(176) = (0.5*(4.13E-12*EXP(452.*TEMP_INV)+1.86E-11*EXP(175.*TEMP_INV)))
  RCONST(177) = (0.5*(1.36E-15*EXP(-2112.*TEMP_INV)+7.51E-16*EXP(-1521.*TEMP_INV)))
  RCONST(178) = (ARR2(2.54E-12,360.))
  RCONST(179) = (ARR2(1.82E-13,1300.))
! RCONST(180) = constant rate coefficient
  RCONST(181) = (TROE(9.7d-29,-5.6d0,9.3d-12,-1.5d0,M,TEMP))
  RCONST(182) = (TROE(9.7d-29,-5.6d0,9.3d-12,-1.5d0,M,TEMP)/(ARR2(9.0E-19,14000.)))
! RCONST(183) = constant rate coefficient
! RCONST(184) = constant rate coefficient
! RCONST(185) = constant rate coefficient
  RCONST(186) = (ARR2(5.60E-12,270.))
  RCONST(187) = (ARR2(1.9E-13,500.))
  RCONST(188) = (ARR2(9.6E-12,-234.))
  RCONST(189) = (ARR2(3.04E-12,350.)*ARR2(1.106E-31,7460.)*M/(1+ARR2(1.106E-31,7460.)*M))
! RCONST(190) = constant rate coefficient
! RCONST(191) = constant rate coefficient
! RCONST(192) = constant rate coefficient
! RCONST(193) = constant rate coefficient
! RCONST(194) = constant rate coefficient
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE kpp_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE kpp_Rates

