/*----------------------- BEGIN box_model_rates.h BEGIN -----------------------*/
/* @file box_model_rates.h                                                     */
/* @author charlesj                                                            */
/* @date 2014-10-09 09:42:21.351284                                            */
/* @brief Reaction rate calculation and utility functions                      */
/*                                                                             */
/* Reaction rate calculation and utility functions                             */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __BOX_MODEL_RATES_H__
#define __BOX_MODEL_RATES_H__



#ifdef __cplusplus
extern "C" {
#endif


/*----------------------------------- Rates -----------------------------------*/
/* Calculates reaction rate coefficients                                       */
/*                                                                             */
/* @param[in]     ncells32 A multiple of 32 grid cells                         */
/* @param[in]     time     Integration time                                    */
/* @param[in]     idx      Current grid cell index                             */
/* @param[in]     TEMP     Temperature (K) (uppercase for KPP compatibility)   */
/* @param[out]    d_rct    Reaction rates in device memory                     */
/*-----------------------------------------------------------------------------*/
void Rates(size_t const ncells32, double const time, size_t const idx,
	   double* d_temp, double* d_rct, double CHI);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __BOX_MODEL_RATES_H__ */
/*------------------------- END box_model_rates.h END -------------------------*/
