! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_Rates.f90
! Time                 : Wed Feb 18 15:16:05 2015
! Working directory    : /users/charlesj/KPP_BOXMODEL/cosmo-art-new/kpp-2.2.3_files_without_NH3
! Equation file        : kpp.kpp
! Output root filename : kpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kpp_Rates

  USE kpp_Precision
  USE kpp_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions



!C
!C*********************************************************************
!C Die Funktion TROE bestimmt die Werte der Troefunktion
!C nach Stockwell et al. [2],
!C die die Druckabhaengigkeit von Reaktionskonstanten durch eine
!C quasi-bimolekulare Reaktionskonstante beschreibt.
!C*********************************************************************
!C
 FUNCTION TROE( K0300, Q, KU300, R, M, T )
!C CALCULATION OF RATE CONSTANTS FOR TROE REACTIONS
!      IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: K0300, Q, KU300, R, M, T, TROE
      REAL(dp) :: tt, k0, ku, k0m, kk, lgkk, e, f
      TT= T / 3.D2
      K0= K0300 / TT**Q
      KU= KU300 / TT**R
      K0M= K0 * M
      KK= K0M / KU
      LGKK=0.434294481D0 * LOG(KK)
      E=1.D0 / ( 1.D0 + LGKK*LGKK )
      F=0.6D0 ** E
      TROE= F * K0M / ( 1.D0 + KK )
END FUNCTION TROE
!C
!C**********************************************************************
!C Die Funktion EQT [2] bestimmt die Reaktionskonstanten fuer
!C HNO4 --> H2O + NO2 und N2O5 --> NO2 + NO3
!C**********************************************************************
!C
FUNCTION EQT( K0300, Q, KU300, R, M, T, A, B )
      !IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: K0300, Q, KU300, R, M, T, A, B, EQT
      REAL(dp) :: kh
      KH= TROE( K0300, Q, KU300, R, M, T )
      EQT= KH * A *DEXP( -B / T )
END FUNCTION EQT
!C
!C**********************************************************************
!C Die Funktion SPEZ bestimmt die Reaktionskonstante fuer
!C HNO3 + HO --> H2O + NO3
!C**********************************************************************
!C
FUNCTION SPEZ(A0,B0,A2,B2,A3,B3,M,T)
!C SPECIAL RATE CONSTANTS
      !IMPLICIT REAL(dp) (A-Z)
      REAL(dp) :: A0,B0,A2,B2,A3,B3,M,T, SPEZ
      REAL(dp) :: k0, k2, k3
      K0=A0*DEXP(B0/T)
      K2=A2*DEXP(B2/T)
      K3=A3*M*DEXP(B3/T)
      SPEZ= K0 + K3 / ( 1 + K3/K2 )
END FUNCTION SPEZ


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE kpp_Parameters
      !USE kpp_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (PHOTO(1))
  RCONST(2) = (PHOTO(2))
  RCONST(3) = (PHOTO(3))
  RCONST(4) = (PHOTO(4))
  RCONST(5) = (PHOTO(5))
  RCONST(6) = (PHOTO(6)+EQT(1.8d-31,3.2d0,4.7d-12,1.4d0,M,TEMP,4.76d+26,10900.d0))
  RCONST(7) = (PHOTO(7))
  RCONST(8) = (PHOTO(8))
  RCONST(9) = (PHOTO(9))
  RCONST(10) = (PHOTO(10))
  RCONST(11) = (PHOTO(11))
  RCONST(12) = (PHOTO(12))
  RCONST(13) = (PHOTO(13))
  RCONST(14) = (PHOTO(14))
  RCONST(15) = (PHOTO(15))
  RCONST(16) = (PHOTO(16))
  RCONST(17) = (PHOTO(17))
  RCONST(18) = (PHOTO(18))
  RCONST(19) = (PHOTO(19))
  RCONST(20) = (PHOTO(20))
  RCONST(21) = (PHOTO(21))
  RCONST(22) = (M*6.0E-34*(TEMP/300.)**(-2.3))
  RCONST(23) = (6.50E-12*EXP(120./TEMP))
  RCONST(24) = (2.00E-11*EXP(130./TEMP))
  RCONST(25) = (3.20E-11*EXP(67./TEMP))
! RCONST(26) = constant rate coefficient
  RCONST(27) = (1.4E-12*EXP(-1310./TEMP))
  RCONST(28) = (1.70E-12*EXP(-940./TEMP))
  RCONST(29) = (1.10E-14*EXP(-500./TEMP))
  RCONST(30) = (3.45E-12*EXP(270./TEMP))
  RCONST(31) = (TROE(1.8D-31,3.2d0,4.7D-12,1.4d0,M,TEMP))
  RCONST(32) = (2.2E-13*EXP(620./TEMP)+1.9E-33*M*EXP(980./TEMP))
  RCONST(33) = (3.08d-34*EXP(2820./TEMP)+2.66d-54*M*EXP(3180./TEMP))
  RCONST(34) = (3.30E-12*EXP(-200./TEMP))
  RCONST(35) = (TROE(7.0d-31,2.6d0,1.5d-11,0.5d0,M,TEMP))
  RCONST(36) = (3.30E-39*EXP(530./TEMP))
  RCONST(37) = (1.40E-13*EXP(-2470./TEMP))
  RCONST(38) = (1.80E-11*EXP(110./TEMP))
  RCONST(39) = (2.50E-14*EXP(-1230./TEMP))
! RCONST(40) = constant rate coefficient
  RCONST(41) = (TROE(2.2d-30,4.3d0,1.5d-12,0.5d0,M,TEMP))
  RCONST(42) = (EQT(2.2d-30,4.3d0,1.5d-12,0.5d0,M,TEMP,9.09d+26,11200.d0))
  RCONST(43) = (HET(1))
  RCONST(44) = (TROE(2.6d-30,3.2d0,2.4d-11,1.3d0,M,TEMP))
  RCONST(45) = (SPEZ(7.2d-15,785.d0,4.1d-16,1440.d0,1.9d-33,725.d0,M,TEMP))
  RCONST(46) = (1.30E-12*EXP(380./TEMP))
  RCONST(47) = (4.80E-11*EXP(250./TEMP))
  RCONST(48) = (TROE(3.0d-31,3.3d0,1.5d-12,0.0d0,M,TEMP))
  RCONST(49) = (1.5E-13*(1.0+2.439E-20*M))
  RCONST(50) = (TEMP*TEMP*6.95E-18*EXP(-1280./TEMP))
  RCONST(51) = (TEMP*TEMP*1.37E-17*EXP(-444./TEMP))
  RCONST(52) = (1.59E-11*EXP(-540./TEMP))
  RCONST(53) = (1.73E-11*EXP(-380./TEMP))
  RCONST(54) = (3.64E-11*EXP(-380./TEMP))
  RCONST(55) = (2.15E-12*EXP(411./TEMP))
  RCONST(56) = (5.32E-12*EXP(504./TEMP))
  RCONST(57) = (1.07E-11*EXP(549./TEMP))
  RCONST(58) = (2.10E-12*EXP(322./TEMP))
  RCONST(59) = (1.89E-11*EXP(116./TEMP))
! RCONST(60) = constant rate coefficient
! RCONST(61) = constant rate coefficient
  RCONST(62) = (6.87E-12*EXP(256./TEMP))
  RCONST(63) = (1.20E-11*EXP(-745./TEMP))
! RCONST(64) = constant rate coefficient
! RCONST(65) = constant rate coefficient
! RCONST(66) = constant rate coefficient
! RCONST(67) = constant rate coefficient
! RCONST(68) = constant rate coefficient
! RCONST(69) = constant rate coefficient
  RCONST(70) = (TEMP*TEMP*6.85E-18*EXP(-444./TEMP))
  RCONST(71) = (1.55E-11*EXP(-540./TEMP))
  RCONST(72) = (2.55E-11*EXP(409./TEMP))
  RCONST(73) = (2.6E-12*EXP(380./TEMP))
  RCONST(74) = (2.E16*EXP(-13500./TEMP))
! RCONST(75) = constant rate coefficient
  RCONST(76) = (1.95E16*EXP(-13543./TEMP))
  RCONST(77) = (4.20E-12*EXP(180./TEMP))
  RCONST(78) = (4.20E-12*EXP(180./TEMP))
  RCONST(79) = (4.20E-12*EXP(180./TEMP))
  RCONST(80) = (4.20E-12*EXP(180./TEMP))
  RCONST(81) = (4.20E-12*EXP(180./TEMP))
  RCONST(82) = (4.20E-12*EXP(180./TEMP))
  RCONST(83) = (4.20E-12*EXP(180./TEMP))
  RCONST(84) = (3.50E-11*EXP(-180./TEMP))
  RCONST(85) = (4.20E-12*EXP(180./TEMP))
  RCONST(86) = (4.20E-12*EXP(180./TEMP))
  RCONST(87) = (4.20E-12*EXP(180./TEMP))
  RCONST(88) = (4.20E-12*EXP(180./TEMP))
  RCONST(89) = (4.20E-12*EXP(180./TEMP))
  RCONST(90) = (4.20E-12*EXP(180./TEMP))
  RCONST(91) = (6.00E-13*EXP(-2058./TEMP))
  RCONST(92) = (1.40E-12*EXP(-1900./TEMP))
  RCONST(93) = (6.00E-13*EXP(-2058./TEMP))
  RCONST(94) = (1.40E-12*EXP(-1900./TEMP))
  RCONST(95) = (1.40E-12*EXP(-1900./TEMP))
! RCONST(96) = constant rate coefficient
  RCONST(97) = (2.00E-12*EXP(-2923./TEMP))
  RCONST(98) = (1.00E-11*EXP(-1895./TEMP))
  RCONST(99) = (3.23E-11*EXP(-975./TEMP))
! RCONST(100) = constant rate coefficient
  RCONST(101) = (1.20E-14*EXP(-2633./TEMP))
  RCONST(102) = (1.32E-14*EXP(-2105./TEMP))
  RCONST(103) = (7.29E-15*EXP(-1136./TEMP))
  RCONST(104) = (1.23E-14*EXP(-2013./TEMP))
  RCONST(105) = (7.70E-14*EXP(1300./TEMP))
  RCONST(106) = (7.70E-14*EXP(1300./TEMP))
  RCONST(107) = (7.70E-14*EXP(1300./TEMP))
  RCONST(108) = (7.70E-14*EXP(1300./TEMP))
  RCONST(109) = (7.70E-14*EXP(1300./TEMP))
  RCONST(110) = (7.70E-14*EXP(1300./TEMP))
  RCONST(111) = (7.70E-14*EXP(1300./TEMP))
  RCONST(112) = (7.70E-14*EXP(1300./TEMP))
  RCONST(113) = (7.70E-14*EXP(1300./TEMP))
  RCONST(114) = (7.70E-14*EXP(1300./TEMP))
  RCONST(115) = (7.70E-14*EXP(1300./TEMP))
  RCONST(116) = (7.70E-14*EXP(1300./TEMP))
  RCONST(117) = (7.70E-14*EXP(1300./TEMP))
  RCONST(118) = (7.70E-14*EXP(1300./TEMP))
  RCONST(119) = (1.90E-13*EXP(220./TEMP))
  RCONST(120) = (1.40E-13*EXP(220./TEMP))
  RCONST(121) = (4.20E-14*EXP(220./TEMP))
  RCONST(122) = (3.40E-14*EXP(220./TEMP))
  RCONST(123) = (2.90E-14*EXP(220./TEMP))
  RCONST(124) = (1.40E-13*EXP(220./TEMP))
  RCONST(125) = (1.40E-13*EXP(220./TEMP))
  RCONST(126) = (1.70E-14*EXP(220./TEMP))
  RCONST(127) = (1.70E-14*EXP(220./TEMP))
  RCONST(128) = (9.60E-13*EXP(220./TEMP))
  RCONST(129) = (1.70E-14*EXP(220./TEMP))
  RCONST(130) = (1.70E-14*EXP(220./TEMP))
  RCONST(131) = (9.60E-13*EXP(220./TEMP))
  RCONST(132) = (3.40E-13*EXP(220./TEMP))
  RCONST(133) = (1.00E-13*EXP(220./TEMP))
  RCONST(134) = (8.40E-14*EXP(220./TEMP))
  RCONST(135) = (7.20E-14*EXP(220./TEMP))
  RCONST(136) = (3.40E-13*EXP(220./TEMP))
  RCONST(137) = (3.40E-13*EXP(220./TEMP))
  RCONST(138) = (4.20E-14*EXP(220./TEMP))
  RCONST(139) = (4.20E-14*EXP(220./TEMP))
  RCONST(140) = (1.19E-12*EXP(220./TEMP))
  RCONST(141) = (4.20E-14*EXP(220./TEMP))
  RCONST(142) = (4.20E-14*EXP(220./TEMP))
  RCONST(143) = (1.19E-12*EXP(220./TEMP))
  RCONST(144) = (7.70E-14*EXP(1300./TEMP))
  RCONST(145) = (1.70E-14*EXP(220./TEMP))
  RCONST(146) = (4.20E-14*EXP(220./TEMP))
  RCONST(147) = (4.20E-12*EXP(180./TEMP))
  RCONST(148) = (4.20E-12*EXP(180./TEMP))
  RCONST(149) = (7.70E-14*EXP(1300./TEMP))
  RCONST(150) = (1.70E-14*EXP(220./TEMP))
  RCONST(151) = (4.20E-14*EXP(220./TEMP))
  RCONST(152) = (1.70E-14*EXP(220./TEMP))
  RCONST(153) = (4.20E-14*EXP(220./TEMP))
  RCONST(154) = (3.60E-16*EXP(220./TEMP))
  RCONST(155) = (1.21E-11*EXP(444./TEMP))
  RCONST(156) = (ARR2(1.19E-12,490.))
  RCONST(157) = (ARR2(1.01E-15,-736.))
! RCONST(158) = constant rate coefficient
! RCONST(159) = constant rate coefficient
  RCONST(160) = (ARR2(3.56E-14,708.))
  RCONST(161) = (ARR2(7.40E-13,765.))
! RCONST(162) = constant rate coefficient
! RCONST(163) = constant rate coefficient
! RCONST(164) = constant rate coefficient
! RCONST(165) = constant rate coefficient
! RCONST(166) = constant rate coefficient
! RCONST(167) = constant rate coefficient
  RCONST(168) = (ARR2(3.56E-14,708.))
  RCONST(169) = (ARR2(7.40E-13,765.))
! RCONST(170) = constant rate coefficient
  RCONST(171) = (ARR2(2.43E-12,360.))
  RCONST(172) = (ARR2(2.05E-13,1300.))
! RCONST(173) = constant rate coefficient
! RCONST(174) = constant rate coefficient
! RCONST(175) = constant rate coefficient
  RCONST(176) = (0.5*(4.13E-12*EXP(452./TEMP)+1.86E-11*EXP(175./TEMP)))
  RCONST(177) = (0.5*(1.36E-15*EXP(-2112./TEMP)+7.51E-16*EXP(-1521./TEMP)))
  RCONST(178) = (ARR2(2.54E-12,360.))
  RCONST(179) = (ARR2(1.82E-13,1300.))
! RCONST(180) = constant rate coefficient
  RCONST(181) = (TROE(9.7d-29,-5.6d0,9.3d-12,-1.5d0,M,TEMP))
  RCONST(182) = (TROE(9.7d-29,-5.6d0,9.3d-12,-1.5d0,M,TEMP)/(ARR2(9.0E-19,14000.)))
! RCONST(183) = constant rate coefficient
! RCONST(184) = constant rate coefficient
! RCONST(185) = constant rate coefficient
  RCONST(186) = (ARR2(5.60E-12,270.))
  RCONST(187) = (ARR2(1.9E-13,500.))
  RCONST(188) = (ARR2(9.6E-12,-234.))
  RCONST(189) = (ARR2(3.04E-12,350.)*ARR2(1.106E-31,7460.)*M/(1+ARR2(1.106E-31,7460.)*M))
! RCONST(190) = constant rate coefficient
! RCONST(191) = constant rate coefficient
! RCONST(192) = constant rate coefficient
! RCONST(193) = constant rate coefficient
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE kpp_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE kpp_Rates

