!-------------------- BEGIN box_model_parameters.f90 BEGIN -------------------
! @file box_model_parameters.f90                                              
! @author charlesj                                                            
! @date 2014-10-15 10:04:26.234147                                            
! @brief Program parameters                                                   
!                                                                             
! Integration tolerances, program constants, and species indices.             
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE box_model_parameters


  IMPLICIT NONE



!-----------------------------------------------------------------------------
! Integration tolerances                                                      
!-----------------------------------------------------------------------------

  ! Absolute tolerance 
  REAL(8), PARAMETER :: ATOLS = 1.0d-2
  ! Relative tolerance 
  REAL(8), PARAMETER :: RTOLS = 1.0d-2


!-----------------------------------------------------------------------------
! Concentration constants                                                     
!-----------------------------------------------------------------------------

  ! Conversion factor 
  REAL(8), PARAMETER :: CFACTOR = 25500000000.0
  ! Default initialization value for variable species 
  REAL(8), PARAMETER :: VAR_DEFAULT = 1e-20
  ! Default initialization value for fixed species 
  REAL(8), PARAMETER :: FIX_DEFAULT = 1e-20


!-----------------------------------------------------------------------------
! Program constants                                                           
!-----------------------------------------------------------------------------

  ! Species count 
  INTEGER, PARAMETER :: NSPEC = 83
  ! Variable species count 
  INTEGER, PARAMETER :: NVAR = 82
  ! Fixed species count 
  INTEGER, PARAMETER :: NFIX = 1
  ! Active variable species count 
  INTEGER, PARAMETER :: NVARACT = 76
  ! Reaction (equation) count 
  INTEGER, PARAMETER :: NREACT = 194
  ! TAG - Day of simulation in the [1:365] interval
  REAL(8), PARAMETER :: TAG = 103. ! 13 April 2010

!-----------------------------------------------------------------------------
! Numerical constants                                                         
!-----------------------------------------------------------------------------

  REAL(8), PARAMETER :: ZERO = 0.0
  REAL(8), PARAMETER :: HALF = 0.5
  REAL(8), PARAMETER :: ONE = 1.0
  REAL(8), PARAMETER :: TWO = 2.0


!-----------------------------------------------------------------------------
! Variable species indices                                                    
!-----------------------------------------------------------------------------

  INTEGER, PARAMETER :: ind_NH3 = 0 
  INTEGER, PARAMETER :: ind_N2 = 1
  INTEGER, PARAMETER :: ind_SULF = 2 
  INTEGER, PARAMETER :: ind_ORA1 = 3 
  INTEGER, PARAMETER :: ind_ORA2 = 4 
  INTEGER, PARAMETER :: ind_CS1 = 5
  INTEGER, PARAMETER :: ind_CO2 = 6 
  INTEGER, PARAMETER :: ind_H2 = 7
  INTEGER, PARAMETER :: ind_ETH = 8 
  INTEGER, PARAMETER :: ind_ISHP = 9 
  INTEGER, PARAMETER :: ind_HC5 = 10 
  INTEGER, PARAMETER :: ind_TPAN = 11 
  INTEGER, PARAMETER :: ind_HONO = 12 
  INTEGER, PARAMETER :: ind_DMSO = 13 
  INTEGER, PARAMETER :: ind_HC8 = 14
  INTEGER, PARAMETER :: ind_SO2 = 15 
  INTEGER, PARAMETER :: ind_N2O5 = 16 
  INTEGER, PARAMETER :: ind_MAHP = 17 
  INTEGER, PARAMETER :: ind_DMS = 18 
  INTEGER, PARAMETER :: ind_TOL = 19 
  INTEGER, PARAMETER :: ind_XYL = 20 
  INTEGER, PARAMETER :: ind_HC3 = 21 
  INTEGER, PARAMETER :: ind_NALD = 22 
  INTEGER, PARAMETER :: ind_CS10 = 23 
  INTEGER, PARAMETER :: ind_CS100 = 24 
  INTEGER, PARAMETER :: ind_CS1000 = 25 
  INTEGER, PARAMETER :: ind_O1D = 26
  INTEGER, PARAMETER :: ind_PAA = 27
  INTEGER, PARAMETER :: ind_MPAN = 28
  INTEGER, PARAMETER :: ind_OP1 = 29
  INTEGER, PARAMETER :: ind_CSL = 30 
  INTEGER, PARAMETER :: ind_HACE = 31 
  INTEGER, PARAMETER :: ind_HNO4 = 32 
  INTEGER, PARAMETER :: ind_PAN = 33
  INTEGER, PARAMETER :: ind_O3P = 34 
  INTEGER, PARAMETER :: ind_H2O2 = 35 
  INTEGER, PARAMETER :: ind_OL2 = 36
  INTEGER, PARAMETER :: ind_ISOP = 37 
  INTEGER, PARAMETER :: ind_ISON = 38 
  INTEGER, PARAMETER :: ind_O2 = 39
  INTEGER, PARAMETER :: ind_API = 40 
  INTEGER, PARAMETER :: ind_CO = 41
  INTEGER, PARAMETER :: ind_LIM = 42 
  INTEGER, PARAMETER :: ind_OLT = 43 
  INTEGER, PARAMETER :: ind_HNO3 = 44 
  INTEGER, PARAMETER :: ind_ISO = 45
  INTEGER, PARAMETER :: ind_GLY = 46 
  INTEGER, PARAMETER :: ind_XNO2 = 47 
  INTEGER, PARAMETER :: ind_XYLP = 48 
  INTEGER, PARAMETER :: ind_MACR = 49 
  INTEGER, PARAMETER :: ind_DCB = 50
  INTEGER, PARAMETER :: ind_HC5P = 51 
  INTEGER, PARAMETER :: ind_HC8P = 52 
  INTEGER, PARAMETER :: ind_OLIP = 53 
  INTEGER, PARAMETER :: ind_KET = 54
  INTEGER, PARAMETER :: ind_OL2P = 55 
  INTEGER, PARAMETER :: ind_OLTP = 56 
  INTEGER, PARAMETER :: ind_XO2 = 57
  INTEGER, PARAMETER :: ind_TOLP = 58 
  INTEGER, PARAMETER :: ind_OP2 = 59
  INTEGER, PARAMETER :: ind_MACP = 60 
  INTEGER, PARAMETER :: ind_OLN = 61
  INTEGER, PARAMETER :: ind_MGLY = 62 
  INTEGER, PARAMETER :: ind_HCHO = 63 
  INTEGER, PARAMETER :: ind_TCO3 = 64
  INTEGER, PARAMETER :: ind_H2O = 65
  INTEGER, PARAMETER :: ind_LIMP = 66
  INTEGER, PARAMETER :: ind_APIP = 67 
  INTEGER, PARAMETER :: ind_OLI = 68
  INTEGER, PARAMETER :: ind_ONIT = 69 
  INTEGER, PARAMETER :: ind_ALD = 70
  INTEGER, PARAMETER :: ind_ETHP = 71 
  INTEGER, PARAMETER :: ind_HO2 = 72
  INTEGER, PARAMETER :: ind_HC3P = 73 
  INTEGER, PARAMETER :: ind_NO2 = 74
  INTEGER, PARAMETER :: ind_MO2 = 75
  INTEGER, PARAMETER :: ind_NO = 76
  INTEGER, PARAMETER :: ind_O3 = 77 
  INTEGER, PARAMETER :: ind_KETP = 78 
  INTEGER, PARAMETER :: ind_NO3 = 79 
  INTEGER, PARAMETER :: ind_ACO3 = 80 
  INTEGER, PARAMETER :: ind_HO = 81

!-----------------------------------------------------------------------------
! Fixed species indices                                                       
!-----------------------------------------------------------------------------

  INTEGER, PARAMETER :: IND_CH4 = 82

!-----------------------------------------------------------------------------
! Reference solution obtained from a previous reference run of 24h 
! on Piz Daint with KPP-2.2.3, Ros4, rtol = atol = 0.01
!-----------------------------------------------------------------------------

  REAL(8), PARAMETER :: ref_sol(8) = &
       (/0.8784400194602625E-02, & ! OP1
       0.9187220281461859E-01, &   ! H2O2
       0.1104451820850433E+01, &   ! HCHO
       0.2311848056029817E+02, &   ! NO2
       0.2784755969096839E-03, &   ! NO
       0.3258921909672916E+01, &   ! O3 
       0.4652958974296319E-03, &   ! NO3
       0.1560354741365994E-06/)    ! HO

END MODULE box_model_parameters
!---------------------- END box_model_parameters.f90 END ---------------------
