!-------------------- BEGIN box_model_integrate.f90 BEGIN --------------------
! @file box_model_integrate.f90                                               
! @author charlesj                                                            
! @date 2014-10-16 17:38:02.829936                                            
! @brief Interface to time stepping integrator                                
!                                                                             
! Definitions of interface functions for the Kppa-generated                   
! time stepping integrator.  These are the Kppa "entry point" routines.       
!                                                                             
! This file was generated by Kppa: http://www.paratools.com/Kppa              
!-----------------------------------------------------------------------------


MODULE box_model_integrate

  USE box_model_parameters
  USE box_model_rosenbrock

  IMPLICIT NONE

  CONTAINS

!------------------------------- GridIntegrate -------------------------------
! Applies the Kppa-generated integrator to the grid                           
!                                                                             
! @param[in]     ncells Number of grid cells                                  
! @param[in,out] conc   Species concentrations                                
! @param[in]     tstart Integration start time                                
! @param[in]     tend   Integration end time                                  
! @param[in]     abstol Absolute integration tolerances for variable species  
! @param[in]     reltol Relative integration tolerances for variable species  
! @param[in,out] idata  Integer integration in/out parameters                 
! @param[in,out] rdata  Real value integration in/out parameters              
!-----------------------------------------------------------------------------
  INTEGER FUNCTION GridIntegrate(ncells, conc, tstart, tend, abstol, reltol, &
      idata, rdata, ISTATS, TEMP)
    IMPLICIT NONE

    INTEGER, INTENT(IN) :: ncells
    REAL(8), INTENT(INOUT) :: conc(NSPEC*ncells)
    REAL(8), INTENT(IN) :: tstart
    REAL(8), INTENT(IN) :: tend
    REAL(8), INTENT(IN) :: abstol(NVAR)
    REAL(8), INTENT(IN) :: reltol(NVAR)
    INTEGER, INTENT(INOUT) :: idata(20)
    REAL(8), INTENT(INOUT) :: rdata(20)
    INTEGER*8, INTENT(OUT) :: ISTATS(8)
    REAL(8), INTENT(IN) :: TEMP(ncells)

    ! Return value 
    INTEGER :: retval
    ! Index to variable concentrations in grid cell
    INTEGER :: var
    ! Index to fixed concentrations in grid cell
    INTEGER :: fix
    ! Iterator
    INTEGER :: i

    retval = 0

    DO i = 1, ncells
        var = (i-1)*NSPEC + 1
        fix = var + NVAR

        ! Invoke the integrator
        CALL Integrate(conc(var), conc(fix), i, tstart, tend, &
             abstol, reltol, idata, rdata, TEMP(i))

        !~~~> Integrator statistics
        ! No. of function calls
        ISTATS(1) = ISTATS(1) + idata(11)
        ! No. of jacobian calls
        ISTATS(2) = ISTATS(2) + idata(12)
        ! No. of steps
        ISTATS(3) = ISTATS(3) + idata(13) 
        ! No. of accepted steps
        ISTATS(4) = ISTATS(4) + idata(14) 
        ! No. of rejected steps (except at very beginning)
        ISTATS(5) = ISTATS(5) + idata(15) 
        ! No. of LU decompositions
        ISTATS(6) = ISTATS(6) + idata(16) 
        ! No. of forward/backward substitutions
        ISTATS(7) = ISTATS(7) + idata(17) 
        ! No. of singular matrix decompositions
        ISTATS(8) = ISTATS(8) + idata(18)

        ! Process integrator return code
        IF (idata(20) < 0) THEN
            WRITE(*,*) "Kppa: CELL",i,"-- INTEGRATION FAILED"
            WRITE(*,*) "Kppa: CELL",i,"idata=",idata
            WRITE(*,*) "Kppa: CELL",i,"rdata=",rdata
            retval = MIN(idata(20), retval)
        ELSE IF (idata(20) > 0) THEN
            WRITE(*,*) "Kppa: CELL",i,"-- INTEGRATION COMPLETED WITH WARNING"
            IF (retval >= 0 .AND. idata(20) > retval) THEN
                retval = idata(20)
            END IF
        END IF
    END DO
    
    GridIntegrate = retval
    RETURN
  END FUNCTION GridIntegrate


END MODULE box_model_integrate
!---------------------- END box_model_integrate.f90 END ----------------------
